# bahamut
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo-lite/geosite/bahamut.list | 规则数: 7
DOMAIN-SUFFIX,bahamut.com.tw
DOMAIN-SUFFIX,digicert.com
DOMAIN-SUFFIX,gamer.com.tw
DOMAIN-SUFFIX,gvt1.com
DOMAIN-SUFFIX,hinet.net
DOMAIN-SUFFIX,viblast.com
DOMAIN,bahamut.akamaized.net
