# 2gis
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/2gis.list | 规则数: 14
DOMAIN-SUFFIX,2gis.cz
DOMAIN-SUFFIX,2gis.uz
DOMAIN-SUFFIX,2gis.az
DOMAIN-SUFFIX,2gis.by
DOMAIN-SUFFIX,2gis.com
DOMAIN-SUFFIX,2gis.tech
DOMAIN-SUFFIX,2gis.kg
DOMAIN-SUFFIX,2gis.ae
DOMAIN-SUFFIX,2gis.am
DOMAIN-SUFFIX,2gis.kz
DOMAIN-SUFFIX,2gis.ru
DOMAIN-SUFFIX,2gis.tj
DOMAIN-SUFFIX,2gis.ge
DOMAIN-SUFFIX,2gis.com.cy
