# 2kgames
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/2kgames.list | 规则数: 6
DOMAIN-SUFFIX,2k.com
DOMAIN-SUFFIX,2kcoretech.online
DOMAIN-SUFFIX,2kct.onl
DOMAIN-SUFFIX,2kgames.com
DOMAIN-SUFFIX,2ksports.com
DOMAIN-SUFFIX,2kweb.online
