# 36kr
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/36kr.list | 规则数: 6
DOMAIN-SUFFIX,36dianping.com
DOMAIN-SUFFIX,36linkr.com
DOMAIN-SUFFIX,36kr.com
DOMAIN-SUFFIX,36krcdn.com
DOMAIN-SUFFIX,36krcnd.com
DOMAIN-SUFFIX,adx.36kr.com
