# 51job
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/51job.list | 规则数: 5
DOMAIN-SUFFIX,51job.com
DOMAIN-SUFFIX,51jobcdn.com
DOMAIN-SUFFIX,yingjiesheng.com
DOMAIN-SUFFIX,yingjiesheng.net
DOMAIN-SUFFIX,zhiding.com.cn
