# 6park
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/6park.list | 规则数: 7
DOMAIN-SUFFIX,6park.com
DOMAIN-SUFFIX,6parkbbs.com
DOMAIN-SUFFIX,6parknews.com
DOMAIN-SUFFIX,cool18.com
DOMAIN-SUFFIX,popo8.com
DOMAIN-SUFFIX,parkvv.com
DOMAIN-SUFFIX,xwbo.com
