# 9news
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/9news.list | 规则数: 14
DOMAIN-SUFFIX,9cdn.net
DOMAIN-SUFFIX,mi9cdn.com
DOMAIN-SUFFIX,9now.com.au
DOMAIN-SUFFIX,9news.com.au
DOMAIN-SUFFIX,freeviewplus.net.au
DOMAIN-SUFFIX,mi9.com.au
DOMAIN-SUFFIX,9nation.com.au
DOMAIN-SUFFIX,nine.com.au
DOMAIN-SUFFIX,nineentertainment.com.au
DOMAIN-SUFFIX,nineentertainmentco.com.au
DOMAIN-SUFFIX,ninemediaroom.com.au
DOMAIN-SUFFIX,ninemsn.com.au
DOMAIN-SUFFIX,static9.net.au
DOMAIN-SUFFIX,yourtv.com.au
