# aamgame
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/aamgame.list | 规则数: 5
DOMAIN-SUFFIX,aamgame.net
DOMAIN-SUFFIX,aamgame.com
DOMAIN-SUFFIX,aamgame.mobi
DOMAIN-SUFFIX,aamsmart.com
DOMAIN-SUFFIX,singworld.net
