# alibaba@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/alibaba@cn.list | 规则数: 4
DOMAIN,account-cn.alibabacloud.com
DOMAIN,api.alibabacloud.com
DOMAIN,cn.alibabacloud.com
DOMAIN,status.alibabacloud.com
