# alibabacloud@!cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/alibabacloud@!cn.list | 规则数: 8
DOMAIN-SUFFIX,alibabacloud.co.in
DOMAIN-SUFFIX,alibabacloud.com
DOMAIN-SUFFIX,alibabacloud.com.au
DOMAIN-SUFFIX,alibabacloud.com.hk
DOMAIN-SUFFIX,alibabacloud.com.my
DOMAIN-SUFFIX,alibabacloud.com.sg
DOMAIN-SUFFIX,alibabacloud.com.tw
DOMAIN-SUFFIX,alicloud.com
