# aliyun@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/aliyun@ads.list | 规则数: 9
DOMAIN-SUFFIX,acjs.aliyun.com
DOMAIN-SUFFIX,adash-emas.cn-hangzhou.aliyuncs.com
DOMAIN-SUFFIX,adash.man.aliyuncs.com
DOMAIN-SUFFIX,alimama.alicdn.com
DOMAIN-SUFFIX,atanx.alicdn.com
DOMAIN-SUFFIX,atanx2.alicdn.com
DOMAIN-SUFFIX,baichuan-sdk.alicdn.com
DOMAIN-SUFFIX,nbsdk-baichuan.alicdn.com
DOMAIN-SUFFIX,tce.alicdn.com
