# amp
# 由 fly-rule 自 metacubex@cb3e075 转换，请勿手工编辑
# 上游: geo/geosite/classical/amp.list | 规则数: 6
DOMAIN,amp.akamaized.net
DOMAIN-SUFFIX,amp.dev
DOMAIN-SUFFIX,ampproject.com
DOMAIN-SUFFIX,ampproject.net
DOMAIN-SUFFIX,ampproject.org
DOMAIN,cdn.ampproject.org
