# anker
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/anker.list | 规则数: 12
DOMAIN-SUFFIX,ankerwork.cn
DOMAIN-SUFFIX,eufycn.com
DOMAIN-SUFFIX,anker.com.cn
DOMAIN-SUFFIX,eufymake.com.cn
DOMAIN-SUFFIX,soundcore.com.cn
DOMAIN-SUFFIX,anker-in.com
DOMAIN-SUFFIX,anker.com
DOMAIN-SUFFIX,ankersolix.com
DOMAIN-SUFFIX,eufy.com
DOMAIN-SUFFIX,eufylife.com
DOMAIN-SUFFIX,eufymake.com
DOMAIN-SUFFIX,soundcore.com
