# apple@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/apple@ads.list | 规则数: 5
DOMAIN-SUFFIX,advertising.apple.com
DOMAIN-SUFFIX,api-adservices.apple.com
DOMAIN-SUFFIX,iadsdk.apple.com
DOMAIN-SUFFIX,iad.apple.com
DOMAIN-SUFFIX,qwapi.com
