# atlassian
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/atlassian.list | 规则数: 11
DOMAIN-SUFFIX,atl-paas.net
DOMAIN-SUFFIX,atlassian-dev.net
DOMAIN-SUFFIX,atlassian.com
DOMAIN-SUFFIX,atlassian.net
DOMAIN-SUFFIX,bitbucket.io
DOMAIN-SUFFIX,bitbucket.org
DOMAIN-SUFFIX,jira.com
DOMAIN-SUFFIX,ss-inf.net
DOMAIN-SUFFIX,statuspage.io
DOMAIN-SUFFIX,trello.com
DOMAIN-SUFFIX,trellocdn.com
