# avaxhome
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/avaxhome.list | 规则数: 7
DOMAIN-SUFFIX,avxhm.se
DOMAIN-SUFFIX,avh.world
DOMAIN-SUFFIX,avxde.org
DOMAIN-SUFFIX,avxhm.is
DOMAIN-SUFFIX,avxlive.icu
DOMAIN-SUFFIX,xsava.xyz
DOMAIN-SUFFIX,zavat.pw
