# bandwagonhost
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/bandwagonhost.list | 规则数: 7
DOMAIN-SUFFIX,bandwagonhost.com
DOMAIN-SUFFIX,bwh1.net
DOMAIN-SUFFIX,bwh8.net
DOMAIN-SUFFIX,bwh81.net
DOMAIN-SUFFIX,bwh88.net
DOMAIN-SUFFIX,bwh89.net
DOMAIN-SUFFIX,bwhstatus.com
