# beisen
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/beisen.list | 规则数: 8
DOMAIN-SUFFIX,beisen.com
DOMAIN-SUFFIX,beisen.cn
DOMAIN-SUFFIX,beisenapp.com
DOMAIN-SUFFIX,beisencloud.com
DOMAIN-SUFFIX,beisenpaas.com
DOMAIN-SUFFIX,bsurl.cc
DOMAIN-SUFFIX,bsurl.cn
DOMAIN-SUFFIX,zhiye.com
