# bilibili-cdn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/bilibili-cdn.list | 规则数: 14
DOMAIN-SUFFIX,bilicdn1.com
DOMAIN-SUFFIX,bilicdn2.com
DOMAIN-SUFFIX,bilicdn3.com
DOMAIN-SUFFIX,bilicdn4.com
DOMAIN-SUFFIX,bilicdn5.com
DOMAIN-SUFFIX,biliimg.com
DOMAIN-SUFFIX,bilivideo.cn
DOMAIN-SUFFIX,bilivideo.com
DOMAIN-SUFFIX,bilivideo.net
DOMAIN-SUFFIX,hdslb.com
DOMAIN-SUFFIX,hdslb.org
DOMAIN-SUFFIX,maoercdn.com
DOMAIN-SUFFIX,mincdn.com
DOMAIN,upos-hz-mirrorakam.akamaized.net
