# bilibili-game
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/bilibili-game.list | 规则数: 6
DOMAIN-SUFFIX,bilibiligame.cn
DOMAIN-SUFFIX,bilibiligame.co
DOMAIN-SUFFIX,bilibiligame.net
DOMAIN-SUFFIX,biligame.co
DOMAIN-SUFFIX,biligame.com
DOMAIN-SUFFIX,biligame.net
