# bohemia
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/bohemia.list | 规则数: 9
DOMAIN-SUFFIX,arma3.com
DOMAIN-SUFFIX,armaplatform.com
DOMAIN-SUFFIX,bistudio.com
DOMAIN-SUFFIX,bohemia.net
DOMAIN-SUFFIX,dayz.com
DOMAIN-SUFFIX,makearmanotwar.com
DOMAIN-SUFFIX,silicagame.com
DOMAIN-SUFFIX,vigorgame.com
DOMAIN-SUFFIX,ylands.com
