# bongacams
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/bongacams.list | 规则数: 5
DOMAIN-SUFFIX,bcicdn.com
DOMAIN-SUFFIX,bcrncdn.com
DOMAIN-SUFFIX,bcvcdn.com
DOMAIN-SUFFIX,bgicdn.com
DOMAIN-SUFFIX,bongacams.com
