# bootcdn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/bootcdn.list | 规则数: 4
DOMAIN-SUFFIX,bootcdn.cn
DOMAIN-SUFFIX,bootcdn.net
DOMAIN-SUFFIX,bootcss.com
DOMAIN-SUFFIX,phpcomposer.com
