# brightcove
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/brightcove.list | 规则数: 14
DOMAIN,bcovlive-a.akamaihd.net
DOMAIN,bcsecure01-a.akamaihd.net
DOMAIN,brightcove.imgix.net
DOMAIN-SUFFIX,bcove.video
DOMAIN-SUFFIX,bcovlive.io
DOMAIN-SUFFIX,bcvp0rtal.com
DOMAIN-SUFFIX,boltdns.net
DOMAIN-SUFFIX,brightcove.com
DOMAIN-SUFFIX,brightcove.net
DOMAIN-SUFFIX,brightcove.services
DOMAIN-SUFFIX,brightcovecdn.com
DOMAIN-SUFFIX,videojs.com
DOMAIN-SUFFIX,zencdn.net
DOMAIN-SUFFIX,zencoder.com
