# canonical
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/canonical.list | 规则数: 12
DOMAIN-SUFFIX,canonical.com
DOMAIN-SUFFIX,launchpad.net
DOMAIN-SUFFIX,launchpadcontent.net
DOMAIN-SUFFIX,launchpadlibrarian.com
DOMAIN-SUFFIX,launchpadlibrarian.net
DOMAIN-SUFFIX,launchpadlibrarian.org
DOMAIN-SUFFIX,snapcraft.io
DOMAIN-SUFFIX,snapstore.io
DOMAIN-SUFFIX,ubuntu.com
DOMAIN-SUFFIX,ubuntu.net
DOMAIN-SUFFIX,ubuntuforums.org
DOMAIN-SUFFIX,ubuntu-touch.io
