# canva
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/canva.list | 规则数: 6
DOMAIN-SUFFIX,affinity.studio
DOMAIN-SUFFIX,canva.com
DOMAIN-SUFFIX,canvastatus.com
DOMAIN-SUFFIX,affinity.api.serifservices.com
DOMAIN-SUFFIX,affinity-beta.s3.amazonaws.com
DOMAIN-SUFFIX,affinity-lessons.s3.amazonaws.com
