# category-urlshortner
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-urlshortner.list | 规则数: 5
DOMAIN-SUFFIX,tinyurl.com
DOMAIN-SUFFIX,bit.ly
DOMAIN-SUFFIX,bitly.com
DOMAIN-SUFFIX,bitly.is
DOMAIN-SUFFIX,shorturl.at
