# category-enterprise-query-platform-cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-enterprise-query-platform-cn.list | 规则数: 13
DOMAIN-SUFFIX,aiqicha.com
DOMAIN-SUFFIX,qyyjt.cn
DOMAIN-SUFFIX,x315.com
DOMAIN-SUFFIX,xcc.cn
DOMAIN-SUFFIX,xinchacha.com
DOMAIN-SUFFIX,aiqicha.cn
DOMAIN-SUFFIX,qichamao.com
DOMAIN-SUFFIX,qcc.com
DOMAIN-SUFFIX,qichacha.com
DOMAIN-SUFFIX,qixin.com
DOMAIN-SUFFIX,jindidata.com
DOMAIN-SUFFIX,tianyancha.com
DOMAIN-SUFFIX,aiqicha.baidu.com
