# category-media@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-media@cn.list | 规则数: 5
DOMAIN-SUFFIX,etnet.com.cn
DOMAIN-SUFFIX,etnetchina.com.cn
DOMAIN-SUFFIX,cn-cdn1.skymansion.net
DOMAIN-SUFFIX,tvbc.com.cn
DOMAIN-SUFFIX,thetype.cloud
