# category-network-security-cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-network-security-cn.list | 规则数: 5
DOMAIN-SUFFIX,cnmstl.net
DOMAIN-SUFFIX,fofa.so
DOMAIN-SUFFIX,t00ls.cc
DOMAIN-SUFFIX,t00ls.net
DOMAIN-SUFFIX,tools.team
