# category-number-verification-cn
# 由 fly-rule 自 metacubex@cb3e075 转换，请勿手工编辑
# 上游: geo/geosite/classical/category-number-verification-cn.list | 规则数: 6
# 跳过 Surge 不支持的 DOMAIN-REGEX 1 条，例: 'DOMAIN-REGEX,^nis.+\\.10010\\.com$'
DOMAIN,id6.me
DOMAIN,opencloud.wostore.cn
DOMAIN,hs.wosms.cn
DOMAIN,enrichgw.10010.com
DOMAIN,hap.10010.com
DOMAIN-SUFFIX,cmpassport.com
