# category-speedtest@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-speedtest@cn.list | 规则数: 17
DOMAIN-SUFFIX,cnspeedtest.cn
DOMAIN-SUFFIX,speed.neu6.edu.cn
DOMAIN-SUFFIX,speed.nju.edu.cn
DOMAIN-SUFFIX,speed.nuaa.edu.cn
DOMAIN-SUFFIX,speed.qlu.edu.cn
DOMAIN-SUFFIX,speed.ujs.edu.cn
DOMAIN-SUFFIX,speed6.ujs.edu.cn
DOMAIN-SUFFIX,speedtest.cn
DOMAIN-SUFFIX,speedtest.mfcyun.com
DOMAIN-SUFFIX,speedtest.shu.edu.cn
DOMAIN-SUFFIX,speedtest.xaut.edu.cn
DOMAIN-SUFFIX,speedtest6.shu.edu.cn
DOMAIN-SUFFIX,test.nju.edu.cn
DOMAIN-SUFFIX,test.ustc.edu.cn
DOMAIN-SUFFIX,test6.nju.edu.cn
DOMAIN-SUFFIX,test6.ustc.edu.cn
DOMAIN-SUFFIX,xnfz.seu.edu.cn
