# category-dev-cn@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-dev-cn@ads.list | 规则数: 6
DOMAIN-SUFFIX,ads.unitychina.cn
DOMAIN-SUFFIX,splash-ads.cdn.unity.cn
DOMAIN-SUFFIX,splash-ads.unitychina.cn
DOMAIN-SUFFIX,unityads.unity.cn
DOMAIN-SUFFIX,unityads.unitychina.cn
DOMAIN-SUFFIX,badjs.weixinbridge.com
