# category-acg
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-acg.list | 规则数: 9
DOMAIN-SUFFIX,bestdori.com
DOMAIN-SUFFIX,colorfulstage.com
DOMAIN-SUFFIX,lapriere.jp
DOMAIN-SUFFIX,magicalmirai.com
DOMAIN-SUFFIX,mikuexpo.com
DOMAIN-SUFFIX,piapro.net
DOMAIN-SUFFIX,snowmiku.com
DOMAIN-SUFFIX,bowlroll.net
DOMAIN-SUFFIX,crypton.co.jp
