# category-mooc-cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-mooc-cn.list | 规则数: 11
DOMAIN,moocs.unipus.cn
DOMAIN,opencourse.pku.edu.cn
DOMAIN,study.163.com
DOMAIN-SUFFIX,chinesemooc.org
DOMAIN-SUFFIX,cnmooc.org
DOMAIN-SUFFIX,icourse163.org
DOMAIN-SUFFIX,icourses.cn
DOMAIN-SUFFIX,mooc.cn
DOMAIN-SUFFIX,openlearning.com
DOMAIN-SUFFIX,pmphmooc.com
DOMAIN-SUFFIX,icve.com.cn
