# category-payment-ir
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-payment-ir.list | 规则数: 17
DOMAIN-SUFFIX,pec.ir
DOMAIN-SUFFIX,vandar.app
DOMAIN-SUFFIX,behpardakht.com
DOMAIN-SUFFIX,bitbarg.me
DOMAIN-SUFFIX,iranicard.ir
DOMAIN-SUFFIX,mydigipay.com
DOMAIN-SUFFIX,pay.ir
DOMAIN-SUFFIX,payping.ir
DOMAIN-SUFFIX,asanpardakht.net
DOMAIN-SUFFIX,zarinpal.com
DOMAIN-SUFFIX,asanpardakht.com
DOMAIN-SUFFIX,sep.ir
DOMAIN-SUFFIX,shaparak.ir
DOMAIN-SUFFIX,sadadpsp.ir
DOMAIN-SUFFIX,vandar.io
DOMAIN-SUFFIX,weswap.digital
DOMAIN-SUFFIX,pep.co.ir
