# category-bank-ru@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-bank-ru@ads.list | 规则数: 9
DOMAIN-SUFFIX,ads.sber.ru
DOMAIN-SUFFIX,clickstream.sberbank.ru
DOMAIN-SUFFIX,neon.click
DOMAIN-SUFFIX,sbermarketing.ru
DOMAIN,error-tracking.megamarket.tech
DOMAIN,metrics.21-school.ru
DOMAIN,sentry.sberauto.com
DOMAIN,tracing-http.megamarket.tech
DOMAIN,visor.sberbank.ru
