# category-travel-ir
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-travel-ir.list | 规则数: 7
DOMAIN-SUFFIX,alibaba.ir
DOMAIN-SUFFIX,flightio.com
DOMAIN-SUFFIX,mrbilit.com
DOMAIN-SUFFIX,tap30.services
DOMAIN-SUFFIX,tap33.me
DOMAIN-SUFFIX,tapsi.cab
DOMAIN-SUFFIX,tapsi.ir
