# category-number-verification-cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-number-verification-cn.list | 规则数: 6
DOMAIN,id6.me
DOMAIN,opencloud.wostore.cn
DOMAIN,hs.wosms.cn
DOMAIN,enrichgw.10010.com
DOMAIN,hap.10010.com
DOMAIN-SUFFIX,cmpassport.com
