# category-games-!cn@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-games-!cn@ads.list | 规则数: 2
DOMAIN-SUFFIX,log-upload-os.hoyoverse.com
DOMAIN-SUFFIX,insights-collector.gog.com
