# category-ads-ir
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-ads-ir.list | 规则数: 7
DOMAIN-SUFFIX,adivery.com
DOMAIN-SUFFIX,adivery.ir
DOMAIN-SUFFIX,kaprila.com
DOMAIN-SUFFIX,najva.com
DOMAIN-SUFFIX,sabavision.com
DOMAIN-SUFFIX,tapsell.ir
DOMAIN-SUFFIX,yektanet.com
