# category-scholar-ir
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/category-scholar-ir.list | 规则数: 8
DOMAIN-SUFFIX,ac.ir
DOMAIN-SUFFIX,edu.ir
DOMAIN-SUFFIX,iranlms.ir
DOMAIN-SUFFIX,jtt.ir
DOMAIN-SUFFIX,sanjesh.org
DOMAIN-SUFFIX,sharif.edu
DOMAIN-SUFFIX,sharif.ir
DOMAIN-SUFFIX,srttu.edu
