# cavporn
# 由 fly-rule 自 metacubex@dad2963 转换，请勿手工编辑
# 上游: geo/geosite/classical/cavporn.list | 规则数: 2
# 跳过 Surge 不支持的 DOMAIN-REGEX 1 条，例: 'DOMAIN-REGEX,(^|\\.)cav1(0[2-9]|1[0-9])\\.com$'
DOMAIN-SUFFIX,cavporn.com
DOMAIN-SUFFIX,cavporn.github.io
