# cern
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/cern.list | 规则数: 7
DOMAIN-SUFFIX,cern
DOMAIN-SUFFIX,ams02.space
DOMAIN-SUFFIX,cern.ch
DOMAIN-SUFFIX,cixp.net
DOMAIN-SUFFIX,dotcernpilot.info
DOMAIN-SUFFIX,ippog.org
DOMAIN-SUFFIX,linearcollider.org
