# cityu-hk
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/cityu-hk.list | 规则数: 4
DOMAIN-SUFFIX,cityu.hk
DOMAIN-SUFFIX,xn--uis44a.xn--j6w193g
DOMAIN-SUFFIX,cityu.edu.hk
DOMAIN-SUFFIX,xn----fr0b94b15d2ue8q7a1o3e.xn--wcvs22d.xn--j6w193g
