# cnbc
# 由 fly-rule 自 metacubex@cb3e075 转换，请勿手工编辑
# 上游: geo/geosite/classical/cnbc.list | 规则数: 4
DOMAIN-SUFFIX,cnbc.com
DOMAIN-SUFFIX,cnbcfm.com
DOMAIN-SUFFIX,nbcuni.com
DOMAIN-SUFFIX,nbcudigitaladops.com
