# colorfulclouds
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/colorfulclouds.list | 规则数: 6
DOMAIN-SUFFIX,caiyunai.com
DOMAIN-SUFFIX,caiyunapp.com
DOMAIN-SUFFIX,caiyuncdn.com
DOMAIN-SUFFIX,colorfulclouds.com
DOMAIN-SUFFIX,colorfulclouds.net
DOMAIN-SUFFIX,xiaomengai.com
