# comssone
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/comssone.list | 规则数: 9
DOMAIN-SUFFIX,comss.club
DOMAIN-SUFFIX,comss.info
DOMAIN-SUFFIX,comss.me
DOMAIN-SUFFIX,comss.net
DOMAIN-SUFFIX,comss.news
DOMAIN-SUFFIX,comss.one
DOMAIN-SUFFIX,comss.online
DOMAIN-SUFFIX,comss.org
DOMAIN-SUFFIX,comss.ru
