# cygames
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/cygames.list | 规则数: 5
DOMAIN-SUFFIX,cygames.jp
DOMAIN-SUFFIX,worldflipper.jp
DOMAIN-SUFFIX,cygames.co.jp
DOMAIN-SUFFIX,worldflipper.akamaized.net
DOMAIN-SUFFIX,umamusume.akamaized.net
