# dailymail
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dailymail.list | 规则数: 17
DOMAIN-SUFFIX,mailonsunday.ie
DOMAIN-SUFFIX,mailonline.com
DOMAIN-SUFFIX,thismon.ee
DOMAIN-SUFFIX,dailymail.com
DOMAIN-SUFFIX,mol.im
DOMAIN-SUFFIX,dailymail.dk
DOMAIN-SUFFIX,dailymailonline.com
DOMAIN-SUFFIX,mailhealth.com
DOMAIN-SUFFIX,dailym.ai
DOMAIN-SUFFIX,mailonline.co.uk
DOMAIN-SUFFIX,dmgmediaprivacy.co.uk
DOMAIN-SUFFIX,mailonsunday.co.uk
DOMAIN-SUFFIX,anm.co.uk
DOMAIN-SUFFIX,metro.co.uk
DOMAIN-SUFFIX,dailymail.com.au
DOMAIN-SUFFIX,thisismoney.co.uk
DOMAIN-SUFFIX,dailymail.co.uk
