# dazn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dazn.list | 规则数: 8
DOMAIN-SUFFIX,dazn.com
DOMAIN-SUFFIX,dazn-api.com
DOMAIN-SUFFIX,dazndn.com
DOMAIN-SUFFIX,daznfeeds.com
DOMAIN-SUFFIX,daznplayer.com
DOMAIN-SUFFIX,daznservices.com
DOMAIN-SUFFIX,indazn.com
DOMAIN-SUFFIX,indaznlab.com
