# ddmaicai
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ddmaicai.list | 规则数: 9
DOMAIN-SUFFIX,100.me
DOMAIN-SUFFIX,ddcorp.net
DOMAIN-SUFFIX,ddfresh.net
DOMAIN-SUFFIX,ddimg.mobi
DOMAIN-SUFFIX,ddmaicai.net
DOMAIN-SUFFIX,ddmc.mobi
DOMAIN-SUFFIX,dduser.mobi
DOMAIN-SUFFIX,ddxq.mobi
DOMAIN-SUFFIX,imaicai.mobi
