# dedao
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dedao.list | 规则数: 10
DOMAIN-SUFFIX,biji.com
DOMAIN-SUFFIX,ddmogo.com
DOMAIN-SUFFIX,dedao.cn
DOMAIN-SUFFIX,igetget.cn
DOMAIN-SUFFIX,igetget.com
DOMAIN-SUFFIX,luojilab.com
DOMAIN-SUFFIX,mogoo.com
DOMAIN-SUFFIX,sao.cn
DOMAIN-SUFFIX,saolife.com
DOMAIN-SUFFIX,umiwi.com
