# dell@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dell@cn.list | 规则数: 7
DOMAIN-SUFFIX,dell-brand.com
DOMAIN-SUFFIX,dell.com.cn
DOMAIN-SUFFIX,dell-alw.com
DOMAIN-SUFFIX,dellemc.com.cn
DOMAIN-SUFFIX,dellmobile.cn
DOMAIN-SUFFIX,delltechnologies.com.cn
DOMAIN-SUFFIX,platform.dell.com
