# didi@!cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/didi@!cn.list | 规则数: 4
DOMAIN-SUFFIX,didi-food.com
DOMAIN-SUFFIX,didiaustralia.blog
DOMAIN-SUFFIX,didiglobal.com
DOMAIN-SUFFIX,didimobility.co.jp
