# digitalocean
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/digitalocean.list | 规则数: 6
DOMAIN-SUFFIX,digitalocean.com
DOMAIN-SUFFIX,digitalocean-ui.com
DOMAIN-SUFFIX,digitaloceanspaces.com
DOMAIN-SUFFIX,do.co
DOMAIN-SUFFIX,nginxconfig.io
DOMAIN-SUFFIX,ondigitalocean.com
