# discoveryplus
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/discoveryplus.list | 规则数: 3
DOMAIN-SUFFIX,disco-api.com
DOMAIN-SUFFIX,discoveryplus.com
DOMAIN-SUFFIX,content-ause1-ur-discovery1.uplynk.com
