# dlercloud
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dlercloud.list | 规则数: 4
DOMAIN-SUFFIX,dlercloud.com
DOMAIN-SUFFIX,dlercloud.org
DOMAIN-SUFFIX,dlercloud.me
DOMAIN-SUFFIX,dleris.best
