# dongjiao
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dongjiao.list | 规则数: 4
DOMAIN-SUFFIX,anmo.com
DOMAIN-SUFFIX,djdjapp.com
DOMAIN-SUFFIX,dongjiao.cc
DOMAIN-SUFFIX,dongjiaoapp.com
