# dongchedi
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dongchedi.list | 规则数: 8
DOMAIN-SUFFIX,dcarapi.com
DOMAIN-SUFFIX,dcarimg.com
DOMAIN-SUFFIX,dcarlive.com
DOMAIN-SUFFIX,dcarstatic.com
DOMAIN-SUFFIX,dcarvod.com
DOMAIN-SUFFIX,dcdapp.com
DOMAIN-SUFFIX,dongchedi.com
DOMAIN-SUFFIX,dongchediapp.com
