# douyu
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/douyu.list | 规则数: 7
DOMAIN-SUFFIX,douyu.com
DOMAIN-SUFFIX,douyu.tv
DOMAIN-SUFFIX,douyucdn.cn
DOMAIN-SUFFIX,douyucdn2.cn
DOMAIN-SUFFIX,douyuscdn.com
DOMAIN-SUFFIX,douyutv.com
DOMAIN-SUFFIX,edgesrv.com
