# dyna
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/dyna.list | 规则数: 5
DOMAIN-SUFFIX,dynacw.com
DOMAIN-SUFFIX,dynacw.co.jp
DOMAIN-SUFFIX,dynacw.com.cn
DOMAIN-SUFFIX,dynacw.com.hk
DOMAIN-SUFFIX,dynacw.com.tw
