# economist
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/economist.list | 规则数: 4
DOMAIN-SUFFIX,economist.com
DOMAIN-SUFFIX,economistgroup.com
DOMAIN-SUFFIX,economistgroupcareers.com
DOMAIN-SUFFIX,eiu.com
