# embl
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/embl.list | 规则数: 7
DOMAIN-SUFFIX,embl-hamburg.de
DOMAIN-SUFFIX,embl.de
DOMAIN-SUFFIX,embl.fr
DOMAIN-SUFFIX,embl.it
DOMAIN-SUFFIX,embl.org
DOMAIN-SUFFIX,emblstatic.net
DOMAIN-SUFFIX,ebi.ac.uk
