# entrust
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/entrust.list | 规则数: 10
DOMAIN-SUFFIX,entrust.cn
DOMAIN-SUFFIX,entrust.com
DOMAIN-SUFFIX,entrust.net
DOMAIN-SUFFIX,entrustdatacard.com
DOMAIN-SUFFIX,affirmtrust.com
DOMAIN-SUFFIX,atos.net
DOMAIN-SUFFIX,myatos.net
DOMAIN-SUFFIX,certificat2.com
DOMAIN-SUFFIX,trendmicro.com
DOMAIN,www.entrust.cn
