# eset
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/eset.list | 规则数: 9
DOMAIN,eset-prod-ca48648d0ce7cadf.elb.eu-central-1.amazonaws.com
DOMAIN,epc-de-agent-proxy.germanywestcentral.cloudapp.azure.com
DOMAIN-SUFFIX,e5.sk
DOMAIN-SUFFIX,eset.com
DOMAIN-SUFFIX,eset.eu
DOMAIN-SUFFIX,eset.sk
DOMAIN-SUFFIX,eset.systems
DOMAIN-SUFFIX,esetsoftware.com
DOMAIN-SUFFIX,cn.eset.com
