# fansta
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/fansta.list | 规则数: 5
DOMAIN,misa-prod.s3.ap-northeast-1.amazonaws.com
DOMAIN-SUFFIX,fansta.me
DOMAIN-SUFFIX,aga-expo.com
DOMAIN-SUFFIX,cosfans-tw.com
DOMAIN-SUFFIX,2023aga.oen.tw
