# fengxing
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/fengxing.list | 规则数: 7
DOMAIN-SUFFIX,fspcdn.com
DOMAIN-SUFFIX,fun.tv
DOMAIN-SUFFIX,funshion.com
DOMAIN-SUFFIX,funshion.net
DOMAIN-SUFFIX,ibidian.com
DOMAIN-SUFFIX,jvcsmart.cn
DOMAIN-SUFFIX,jvcsmart.com.cn
