# ficbook
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ficbook.list | 规则数: 6
DOMAIN-SUFFIX,fanfictionero.com
DOMAIN-SUFFIX,fic.fan
DOMAIN-SUFFIX,ficador.com
DOMAIN-SUFFIX,ficbook.net
DOMAIN-SUFFIX,ficmania.com
DOMAIN-SUFFIX,teinon.net
