# firefox
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/firefox.list | 规则数: 8
DOMAIN,mozilla-ohttp.fastly-edge.com
DOMAIN,mozilla.map.fastly.net
DOMAIN-SUFFIX,extendfirefox.com
DOMAIN-SUFFIX,firefox-portal-detection.com
DOMAIN-SUFFIX,firefox.com
DOMAIN-SUFFIX,firefox.hu
DOMAIN-SUFFIX,firefoxtweetmachine.com
DOMAIN-SUFFIX,firefoxusercontent.com
