# focuschina
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/focuschina.list | 规则数: 5
DOMAIN-SUFFIX,focuschina.com
DOMAIN-SUFFIX,made-in-china.com
DOMAIN-SUFFIX,micstatic.com
DOMAIN-SUFFIX,trademessenger.com
DOMAIN-SUFFIX,vemic.com
