# forza
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/forza.list | 规则数: 5
DOMAIN,prodforza.blob.core.windows.net
DOMAIN-SUFFIX,forza.net
DOMAIN-SUFFIX,forzamotorsport.net
DOMAIN-SUFFIX,forzaracingchampionship.com
DOMAIN-SUFFIX,forzarc.com
