# gamersky@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/gamersky@ads.list | 规则数: 5
DOMAIN-SUFFIX,click.gamersky.com
DOMAIN-SUFFIX,ja.gamersky.com
DOMAIN-SUFFIX,ja1.gamersky.com
DOMAIN-SUFFIX,ja2.gamersky.com
DOMAIN-SUFFIX,wmbd.gamersky.com
