# genotek-ru
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/genotek-ru.list | 规则数: 9
DOMAIN-SUFFIX,genetic-technologies.am
DOMAIN-SUFFIX,genotek.am
DOMAIN-SUFFIX,genotek.es
DOMAIN-SUFFIX,genotek.eu
DOMAIN-SUFFIX,genotek.health
DOMAIN-SUFFIX,genotek.ru
DOMAIN-SUFFIX,eligens.cl
DOMAIN-SUFFIX,eligens.io
DOMAIN-SUFFIX,eligens.com.br
