# getui
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/getui.list | 规则数: 7
DOMAIN-SUFFIX,gepush.com
DOMAIN-SUFFIX,getui.cn
DOMAIN-SUFFIX,getui.com
DOMAIN-SUFFIX,getui.net
DOMAIN-SUFFIX,igehuo.com
DOMAIN-SUFFIX,igetui.com
DOMAIN-SUFFIX,igexin.com
