# gismeteo
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/gismeteo.list | 规则数: 7
DOMAIN-SUFFIX,gismeteo.by
DOMAIN-SUFFIX,gismeteo.com
DOMAIN-SUFFIX,gismeteo.net
DOMAIN-SUFFIX,gismeteo.ru
DOMAIN-SUFFIX,gismeteo.st
DOMAIN-SUFFIX,meteofor.com
DOMAIN-SUFFIX,meteofor.st
