# github-copilot
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/github-copilot.list | 规则数: 6
DOMAIN,copilot-proxy.githubusercontent.com
DOMAIN,copilot-workspace.githubnext.com
DOMAIN,copilotprodattachments.blob.core.windows.net
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN,copilot-telemetry-service.githubusercontent.com
DOMAIN,copilot-telemetry.githubusercontent.com
