# gog
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/gog.list | 规则数: 8
DOMAIN,gog-cdn-lumen.secure2.footprint.net
DOMAIN,gog-cdn.akamaized.net
DOMAIN-SUFFIX,gog.com
DOMAIN-SUFFIX,gog-services.com
DOMAIN-SUFFIX,gog-statics.com
DOMAIN-SUFFIX,gogalaxy.com
DOMAIN,gog.qtlglb.com
DOMAIN-SUFFIX,insights-collector.gog.com
