# google-registry-tld
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/google-registry-tld.list | 规则数: 20
DOMAIN-SUFFIX,meme
DOMAIN-SUFFIX,ing
DOMAIN-SUFFIX,foo
DOMAIN-SUFFIX,zip
DOMAIN-SUFFIX,mov
DOMAIN-SUFFIX,nexus
DOMAIN-SUFFIX,dad
DOMAIN-SUFFIX,phd
DOMAIN-SUFFIX,prof
DOMAIN-SUFFIX,esq
DOMAIN-SUFFIX,rsvp
DOMAIN-SUFFIX,boo
DOMAIN-SUFFIX,day
DOMAIN-SUFFIX,new
DOMAIN-SUFFIX,dev
DOMAIN-SUFFIX,page
DOMAIN-SUFFIX,app
DOMAIN-SUFFIX,how
DOMAIN-SUFFIX,soy
DOMAIN-SUFFIX,xn--q9jyb4c
