# hanyi
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hanyi.list | 规则数: 7
DOMAIN,hellofontpreview.oss-cn-beijing.aliyuncs.com
DOMAIN,hellowebfonts.oss-cn-beijing.aliyuncs.com
DOMAIN-SUFFIX,hanyi.com
DOMAIN-SUFFIX,hellofont.cn
DOMAIN-SUFFIX,hellowebfont.com
DOMAIN-SUFFIX,hanyi.com.cn
DOMAIN-SUFFIX,fontstar.com.cn
