# hashicorp
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hashicorp.list | 规则数: 8
DOMAIN-SUFFIX,consul.io
DOMAIN-SUFFIX,hashicorp.com
DOMAIN-SUFFIX,nomadproject.io
DOMAIN-SUFFIX,packer.io
DOMAIN-SUFFIX,terraform.io
DOMAIN-SUFFIX,vagrantcloud.com
DOMAIN-SUFFIX,vagrantup.com
DOMAIN-SUFFIX,vaultproject.io
