# hentaivn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hentaivn.list | 规则数: 4
DOMAIN-SUFFIX,hentaivn.de
DOMAIN-SUFFIX,hentaivn.la
DOMAIN-SUFFIX,hentaivn.net
DOMAIN-SUFFIX,htvncdn.net
