# herogame
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/herogame.list | 规则数: 5
DOMAIN-SUFFIX,hero.com
DOMAIN-SUFFIX,herogame.com
DOMAIN-SUFFIX,heroesports.com
DOMAIN-SUFFIX,shyxhy.com
DOMAIN-SUFFIX,yingxiong.com
