# heroku
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/heroku.list | 规则数: 12
DOMAIN-SUFFIX,heroku.co
DOMAIN-SUFFIX,heroku.com
DOMAIN-SUFFIX,heroku.me
DOMAIN-SUFFIX,herokuapp.com
DOMAIN-SUFFIX,herokucdn.com
DOMAIN-SUFFIX,herokucharge.com
DOMAIN-SUFFIX,herokussl.com
DOMAIN-SUFFIX,heroku-app.com
DOMAIN-SUFFIX,heroku-charge.com
DOMAIN-SUFFIX,codei.sh
DOMAIN-SUFFIX,codeish.co
DOMAIN-SUFFIX,codeish.io
