# hikvision
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hikvision.list | 规则数: 8
DOMAIN-SUFFIX,hik-cloud.com
DOMAIN-SUFFIX,hik-express.com
DOMAIN-SUFFIX,hikiot.com
DOMAIN-SUFFIX,hikmall.com
DOMAIN-SUFFIX,hikvision.com
DOMAIN-SUFFIX,eziot.com
DOMAIN-SUFFIX,ezviz.com
DOMAIN-SUFFIX,ys7.com
