# hkbn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hkbn.list | 规则数: 6
DOMAIN-SUFFIX,csifund.org
DOMAIN-SUFFIX,hkbn.net
DOMAIN-SUFFIX,hkbnes.net
DOMAIN-SUFFIX,jos.com
DOMAIN-SUFFIX,hkbn.com.hk
DOMAIN-SUFFIX,speedtest.com.hk
