# hotstar
# 由 fly-rule 自 metacubex@dad2963 转换，请勿手工编辑
# 上游: geo/geosite/classical/hotstar.list | 规则数: 5
# 跳过 Surge 不支持的 DOMAIN-REGEX 1 条，例: 'DOMAIN-REGEX,^hses[1-7]?\\.akamaized\\.net$'
DOMAIN-SUFFIX,hotstar.com
DOMAIN-SUFFIX,hotstar-cdn.net
DOMAIN-SUFFIX,hotstar-labs.com
DOMAIN-SUFFIX,hotstarext.com
DOMAIN-SUFFIX,hsprepack.akamaized.net
