# hunantv
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hunantv.list | 规则数: 13
DOMAIN-SUFFIX,hifuntv.com
DOMAIN-SUFFIX,hitv.com
DOMAIN-SUFFIX,hnbntv.com
DOMAIN-SUFFIX,hunaniptv.com
DOMAIN-SUFFIX,hunantv.com
DOMAIN-SUFFIX,imgo.tv
DOMAIN-SUFFIX,mgtv.com
DOMAIN-SUFFIX,click.hunantv.com
DOMAIN-SUFFIX,da.hunantv.com
DOMAIN-SUFFIX,da.mgtv.com
DOMAIN-SUFFIX,log.hunantv.com
DOMAIN-SUFFIX,log.v2.hunantv.com
DOMAIN-SUFFIX,res.hunantv.com
