# hupun
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/hupun.list | 规则数: 5
DOMAIN-SUFFIX,hupun.com
DOMAIN-SUFFIX,newniu.com
DOMAIN-SUFFIX,wanliniu.com
DOMAIN-SUFFIX,hupun.com.cn
DOMAIN-SUFFIX,kata.com.cn
