# insider
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/insider.list | 规则数: 16
DOMAIN-SUFFIX,businessinsider.jp
DOMAIN-SUFFIX,businessinsider.mx
DOMAIN-SUFFIX,insiderintelligence.com
DOMAIN-SUFFIX,insider.com
DOMAIN-SUFFIX,businessinsider.de
DOMAIN-SUFFIX,businessinsider.es
DOMAIN-SUFFIX,businessinsider.com
DOMAIN-SUFFIX,businessinsider.fr
DOMAIN-SUFFIX,insider-intelligence.com
DOMAIN-SUFFIX,businessinsider.in
DOMAIN-SUFFIX,businessinsider.my
DOMAIN-SUFFIX,businessinsider.nl
DOMAIN-SUFFIX,businessinsider.sg
DOMAIN-SUFFIX,businessinsider.co.za
DOMAIN-SUFFIX,businessinsider.com.pl
DOMAIN-SUFFIX,businessinsider.com.au
