# intercom
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/intercom.list | 规则数: 4
DOMAIN-SUFFIX,intercom.com
DOMAIN-SUFFIX,intercom.io
DOMAIN-SUFFIX,intercomassets.com
DOMAIN-SUFFIX,intercomcdn.com
