# intsig
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/intsig.list | 规则数: 5
DOMAIN-SUFFIX,intsig.com
DOMAIN-SUFFIX,intsig.net
DOMAIN-SUFFIX,camscanner.com
DOMAIN-SUFFIX,camcard.com
DOMAIN-SUFFIX,qixin.com
