# ishumei
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ishumei.list | 规则数: 10
DOMAIN-SUFFIX,ishumei.com
DOMAIN-SUFFIX,fengkongbao.com
DOMAIN-SUFFIX,fengkongcloud.com
DOMAIN-SUFFIX,fengkongcloud.cn
DOMAIN-SUFFIX,portal101.cn
DOMAIN-SUFFIX,portal102.cn
DOMAIN-SUFFIX,portal201.cn
DOMAIN-SUFFIX,portal301.cn
DOMAIN-SUFFIX,tebiefuza.cloud
DOMAIN-SUFFIX,tebiefuza.cn
