# ixbt
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ixbt.list | 规则数: 9
DOMAIN-SUFFIX,ixbt.com
DOMAIN-SUFFIX,ixbt.games
DOMAIN-SUFFIX,ixbt.pro
DOMAIN-SUFFIX,ixbt.ru
DOMAIN-SUFFIX,ixbt.market
DOMAIN-SUFFIX,ixbt.media
DOMAIN-SUFFIX,ixbt.shop
DOMAIN-SUFFIX,ixbt.site
DOMAIN-SUFFIX,ixbt.video
