# jd@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/jd@ads.list | 规则数: 8
DOMAIN-SUFFIX,ads-union.jd.com
DOMAIN-SUFFIX,ads.union.jd.com
DOMAIN-SUFFIX,c-nfa.jd.com
DOMAIN-SUFFIX,cps.360buy.com
DOMAIN-SUFFIX,gia.jd.com
DOMAIN-SUFFIX,img-x.jd.com
DOMAIN-SUFFIX,jzt.jd.com
DOMAIN-SUFFIX,stat.m.jd.com
