# jfrog
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/jfrog.list | 规则数: 4
DOMAIN,d29vzk4ow07wi7.cloudfront.net
DOMAIN-SUFFIX,jfrog.com
DOMAIN-SUFFIX,jfrog.org
DOMAIN-SUFFIX,bintray.com
