# jiemian
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/jiemian.list | 规则数: 8
DOMAIN-SUFFIX,cailianpress.com
DOMAIN-SUFFIX,chinastarmarket.cn
DOMAIN-SUFFIX,cls.cn
DOMAIN-SUFFIX,jiemian.com
DOMAIN-SUFFIX,jingpt.com
DOMAIN-SUFFIX,lanjinger.com
DOMAIN-SUFFIX,moer.cn
DOMAIN-SUFFIX,jiemian.com.cn
