# jwplayer
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/jwplayer.list | 规则数: 6
DOMAIN-SUFFIX,jwpcdn.com
DOMAIN-SUFFIX,jwplatform.com
DOMAIN-SUFFIX,jwplayer.com
DOMAIN-SUFFIX,jwpltx.com
DOMAIN-SUFFIX,jwpsrv.com
DOMAIN-SUFFIX,longtailvideo.com
