# kaggle
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/kaggle.list | 规则数: 4
DOMAIN-SUFFIX,kaggle.com
DOMAIN-SUFFIX,kaggle.io
DOMAIN-SUFFIX,kaggle.net
DOMAIN-SUFFIX,kaggleusercontent.com
