# kanzhongguo
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/kanzhongguo.list | 规则数: 16
DOMAIN-SUFFIX,es-visiontimes.com
DOMAIN-SUFFIX,kannewyork.com
DOMAIN-SUFFIX,kanzhongguo.com
DOMAIN-SUFFIX,kanzhongguo.eu
DOMAIN-SUFFIX,secretchina.com
DOMAIN-SUFFIX,trithucvn.net
DOMAIN-SUFFIX,trithucvn.org
DOMAIN-SUFFIX,vct.news
DOMAIN-SUFFIX,visiontimes.com
DOMAIN-SUFFIX,visiontimes.de
DOMAIN-SUFFIX,visiontimes.fr
DOMAIN-SUFFIX,visiontimes.it
DOMAIN-SUFFIX,visiontimes.net
DOMAIN-SUFFIX,visiontimesjp.com
DOMAIN-SUFFIX,vtvan.com
DOMAIN-SUFFIX,watchinese.com
