# keep
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/keep.list | 规则数: 5
DOMAIN-SUFFIX,calorietech.com
DOMAIN-SUFFIX,gotokeep.com
DOMAIN-SUFFIX,keep.com
DOMAIN-SUFFIX,keepcdn.com
DOMAIN-SUFFIX,keep.com.cn
