# kinopub
# 由 fly-rule 自 metacubex@cb3e075 转换，请勿手工编辑
# 上游: geo/geosite/classical/kinopub.list | 规则数: 17
# 跳过 Surge 不支持的 DOMAIN-REGEX 1 条，例: 'DOMAIN-REGEX,(\\w+)-static-[0-9]+\\.cdntogo\\.net$'
DOMAIN-SUFFIX,cdn-service.space
DOMAIN-SUFFIX,cdn2cdn.com
DOMAIN-SUFFIX,kinopub.online
DOMAIN-SUFFIX,kpdl.link
DOMAIN-SUFFIX,ahc.ovh
DOMAIN-SUFFIX,gfw.ovh
DOMAIN-SUFFIX,tsx.ovh
DOMAIN-SUFFIX,mos-gorsud.co
DOMAIN-SUFFIX,kino.watch
DOMAIN-SUFFIX,smarttvcdn.online
DOMAIN-SUFFIX,pushbr.com
DOMAIN-SUFFIX,teleos.club
DOMAIN-SUFFIX,kino.pub
DOMAIN-SUFFIX,support-kp.com
DOMAIN-SUFFIX,cdn2site.com
DOMAIN-SUFFIX,api.alador.space
DOMAIN-SUFFIX,m.alador.space
