# kinopub
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/kinopub.list | 规则数: 17
DOMAIN-SUFFIX,cdn-service.space
DOMAIN-SUFFIX,cdn2cdn.com
DOMAIN-SUFFIX,kinopub.online
DOMAIN-SUFFIX,kpdl.link
DOMAIN-SUFFIX,ahc.ovh
DOMAIN-SUFFIX,gfw.ovh
DOMAIN-SUFFIX,tsx.ovh
DOMAIN-SUFFIX,mos-gorsud.co
DOMAIN-SUFFIX,kino.watch
DOMAIN-SUFFIX,smarttvcdn.online
DOMAIN-SUFFIX,pushbr.com
DOMAIN-SUFFIX,teleos.club
DOMAIN-SUFFIX,kino.pub
DOMAIN-SUFFIX,support-kp.com
DOMAIN-SUFFIX,cdn2site.com
DOMAIN-SUFFIX,api.alador.space
DOMAIN-SUFFIX,m.alador.space
