# kkbox
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/kkbox.list | 规则数: 5
DOMAIN-SUFFIX,kfs.io
DOMAIN-SUFFIX,kk.stream
DOMAIN-SUFFIX,kkbox.com
DOMAIN-SUFFIX,kktix.com
DOMAIN-SUFFIX,kkbox.com.tw
