# kodik
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/kodik.list | 规则数: 5
DOMAIN-SUFFIX,kodik-storage.com
DOMAIN-SUFFIX,kodik.biz
DOMAIN-SUFFIX,kodik.cc
DOMAIN-SUFFIX,kodik.info
DOMAIN-SUFFIX,kodikplayer.com
