# kurogames@!cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/kurogames@!cn.list | 规则数: 5
DOMAIN-SUFFIX,kurogame-service.com
DOMAIN-SUFFIX,kurogame.net
DOMAIN-SUFFIX,kurogames.net
DOMAIN-SUFFIX,aki-game.net
DOMAIN-SUFFIX,aki-game2.net
