# landian
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/landian.list | 规则数: 7
DOMAIN-SUFFIX,landian.news
DOMAIN-SUFFIX,lancdn.com
DOMAIN-SUFFIX,landiannews.com
DOMAIN-SUFFIX,landian.vip
DOMAIN-SUFFIX,landian.xyz
DOMAIN-SUFFIX,ourl.co
DOMAIN-SUFFIX,wsoso.com
