# le@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/le@ads.list | 规则数: 4
DOMAIN-SUFFIX,apple.www.letv.com
DOMAIN-SUFFIX,ark.letv.com
DOMAIN-SUFFIX,dc.letv.com
DOMAIN-SUFFIX,g3.letv.com
