# limelight
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/limelight.list | 规则数: 8
DOMAIN-SUFFIX,delvenetworks.com
DOMAIN-SUFFIX,limelight.com
DOMAIN-SUFFIX,lldns.net
DOMAIN-SUFFIX,llnw-trials.com
DOMAIN-SUFFIX,llnw.com
DOMAIN-SUFFIX,llnw.net
DOMAIN-SUFFIX,llnwd.net
DOMAIN-SUFFIX,llnwi.net
