# lizhi
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/lizhi.list | 规则数: 6
DOMAIN-SUFFIX,gzlzfm.com
DOMAIN-SUFFIX,lizhi.fm
DOMAIN-SUFFIX,lizhifm.com
DOMAIN-SUFFIX,lizhiinc.com
DOMAIN-SUFFIX,lz310.com
DOMAIN-SUFFIX,lzpipi.com
