# longbridge
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/longbridge.list | 规则数: 12
DOMAIN-SUFFIX,longbridge.cloud
DOMAIN-SUFFIX,longbridge.cn
DOMAIN-SUFFIX,longbridge.com
DOMAIN-SUFFIX,longbridge.global
DOMAIN-SUFFIX,longbridge.hk
DOMAIN-SUFFIX,longbridge.sg
DOMAIN-SUFFIX,longbridgeapp.com
DOMAIN-SUFFIX,longbridgehk.com
DOMAIN-SUFFIX,longportapp.com
DOMAIN-SUFFIX,lbctrl.com
DOMAIN-SUFFIX,lbkrs.com
DOMAIN-SUFFIX,wbrks.com
