# lumion
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/lumion.list | 规则数: 6
DOMAIN-SUFFIX,lumion-la.com
DOMAIN-SUFFIX,lumion.com
DOMAIN-SUFFIX,lumion3d.net
DOMAIN-SUFFIX,lumiontech.net
DOMAIN-SUFFIX,mylumion.com
DOMAIN-SUFFIX,lumion3d.com.my
