# lysol
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/lysol.list | 规则数: 9
DOMAIN-SUFFIX,lysol.ca
DOMAIN-SUFFIX,lysol.cl
DOMAIN-SUFFIX,lysol.com
DOMAIN-SUFFIX,lysol.net
DOMAIN-SUFFIX,lizol.co.in
DOMAIN-SUFFIX,lysol.co.cr
DOMAIN-SUFFIX,lysol.com.mx
DOMAIN-SUFFIX,lysol.cn
DOMAIN-SUFFIX,lysol.com.cn
