# mainichi
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mainichi.list | 规则数: 10
DOMAIN-SUFFIX,machigoto.jp
DOMAIN-SUFFIX,mainichi-athletepartners.jp
DOMAIN-SUFFIX,mainichi.jp
DOMAIN-SUFFIX,mainichibooks.com
DOMAIN-SUFFIX,meijinsen.jp
DOMAIN-SUFFIX,mirailab.tech
DOMAIN-SUFFIX,mottainai.info
DOMAIN-SUFFIX,newsgawakaru.com
DOMAIN-SUFFIX,weekly-economist.com
DOMAIN-SUFFIX,sponichi.co.jp
