# matters
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/matters.list | 规则数: 4
DOMAIN-SUFFIX,matters.news
DOMAIN-SUFFIX,matters.one
DOMAIN-SUFFIX,matters.town
DOMAIN-SUFFIX,mattersprotocol.io
