# mdn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mdn.list | 规则数: 9
DOMAIN,mdn.mozillademos.org
DOMAIN-SUFFIX,mdn.dev
DOMAIN-SUFFIX,mdnplay.dev
DOMAIN-SUFFIX,mdnyalp.dev
DOMAIN-SUFFIX,developer.allizom.org
DOMAIN-SUFFIX,developer.mozilla.org
DOMAIN-SUFFIX,mdn.allizom.net
DOMAIN-SUFFIX,mdn.mozilla.net
DOMAIN-SUFFIX,mdn.mozit.cloud
