# meadjohnson
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/meadjohnson.list | 规则数: 6
DOMAIN-SUFFIX,meadjohnson.com
DOMAIN-SUFFIX,meadjohnson.net
DOMAIN-SUFFIX,meadjohnson.com.hk
DOMAIN-SUFFIX,meadjohnson.com.tw
DOMAIN-SUFFIX,enfinitas.com.cn
DOMAIN-SUFFIX,meadjohnson.com.cn
