# meizu
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/meizu.list | 规则数: 6
DOMAIN-SUFFIX,flyme.cn
DOMAIN-SUFFIX,flyme.com
DOMAIN-SUFFIX,flymeauto.com
DOMAIN-SUFFIX,meizu.cn
DOMAIN-SUFFIX,meizu.com
DOMAIN-SUFFIX,mzres.com
