# microsoft-pki
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/microsoft-pki.list | 规则数: 6
DOMAIN,crl.microsoft.com
DOMAIN,mscrl.microsoft.com
DOMAIN,ocsp.microsoft.com
DOMAIN,oneocsp.microsoft.com
DOMAIN,www.microsoft.com
DOMAIN-SUFFIX,msocsp.com
