# microsoft-dev@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/microsoft-dev@cn.list | 规则数: 4
DOMAIN-SUFFIX,microsoftreactor.cn
DOMAIN-SUFFIX,microsoftreactor.com.cn
DOMAIN-SUFFIX,reactorms.com.cn
DOMAIN,download.visualstudio.microsoft.com
