# microsoft@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/microsoft@ads.list | 规则数: 10
DOMAIN-SUFFIX,clarity.ms
DOMAIN-SUFFIX,microsoftads.com
DOMAIN-SUFFIX,msads.net
DOMAIN-SUFFIX,nelreports.net
DOMAIN-SUFFIX,browser.events.data.msn.cn
DOMAIN-SUFFIX,browser.events.data.msn.com
DOMAIN-SUFFIX,bingads.com
DOMAIN-SUFFIX,collector.github.com
DOMAIN,copilot-telemetry-service.githubusercontent.com
DOMAIN,copilot-telemetry.githubusercontent.com
