# midea
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/midea.list | 规则数: 9
DOMAIN-SUFFIX,irsnp.com
DOMAIN-SUFFIX,mdcdn.cn
DOMAIN-SUFFIX,midea.cn
DOMAIN-SUFFIX,midea.com
DOMAIN-SUFFIX,mideaepayuat.com
DOMAIN-SUFFIX,msmartlife.cn
DOMAIN-SUFFIX,msmartlife.com
DOMAIN-SUFFIX,smartmidea.net
DOMAIN-SUFFIX,midea.com.cn
