# mikrotik
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mikrotik.list | 规则数: 4
DOMAIN-SUFFIX,mikrotik.com
DOMAIN-SUFFIX,mt.lv
DOMAIN-SUFFIX,mynetname.net
DOMAIN-SUFFIX,routerboard.com
