# mindbox@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mindbox@ads.list | 规则数: 10
DOMAIN-SUFFIX,e.mindbox.ru
DOMAIN-SUFFIX,g.mindbox.ru
DOMAIN-SUFFIX,s.mindbox.ru
DOMAIN,api-js.mindbox.ru
DOMAIN,api-ru.mindbox.cloud
DOMAIN,api-staging.mindbox.ru
DOMAIN,api.mindbox.cloud
DOMAIN,api.mindbox.ru
DOMAIN,sentry.mindbox.ru
DOMAIN,sentry.popmechanic.ru
