# missav
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/missav.list | 规则数: 7
DOMAIN-SUFFIX,missav.ai
DOMAIN-SUFFIX,missav.com
DOMAIN-SUFFIX,missav.live
DOMAIN-SUFFIX,missav.uno
DOMAIN-SUFFIX,missav.vip
DOMAIN-SUFFIX,missav.ws
DOMAIN-SUFFIX,missav123.com
