# moji
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/moji.list | 规则数: 7
DOMAIN-SUFFIX,airnut.com
DOMAIN-SUFFIX,moji.com
DOMAIN-SUFFIX,moji001.com
DOMAIN-SUFFIX,moji002.com
DOMAIN-SUFFIX,mojicdn.com
DOMAIN-SUFFIX,mojichina.com
DOMAIN-SUFFIX,ad.api.moji.com
