# monotype
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/monotype.list | 规则数: 14
DOMAIN,fontshop-prod-responsive-images.s3.amazonaws.com
DOMAIN-SUFFIX,monotype.com
DOMAIN-SUFFIX,monotypeimaging.com
DOMAIN-SUFFIX,bitstream.com
DOMAIN-SUFFIX,itcfonts.com
DOMAIN-SUFFIX,fontexplorerx.com
DOMAIN-SUFFIX,fonts.com
DOMAIN-SUFFIX,fonts.net
DOMAIN-SUFFIX,fontbook.com
DOMAIN-SUFFIX,fontshop.com
DOMAIN-SUFFIX,fstopimages.com
DOMAIN-SUFFIX,linotype.com
DOMAIN-SUFFIX,myfonts.com
DOMAIN-SUFFIX,myfonts.net
