# movefree
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/movefree.list | 规则数: 7
DOMAIN-SUFFIX,keepmovingwithmovefree.com
DOMAIN-SUFFIX,move-free.net
DOMAIN-SUFFIX,movefrees.com
DOMAIN-SUFFIX,movefreeoffers.com
DOMAIN-SUFFIX,movefreerewards.com
DOMAIN-SUFFIX,schiffvitamins.com
DOMAIN-SUFFIX,movefree.cn
