# mucinex
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mucinex.list | 规则数: 8
DOMAIN-SUFFIX,mucinex.ca
DOMAIN-SUFFIX,mucinex.cn
DOMAIN-SUFFIX,mucinex.com
DOMAIN-SUFFIX,mucinex.net
DOMAIN-SUFFIX,mucinex.tv
DOMAIN-SUFFIX,mucinexprofessional.com
DOMAIN-SUFFIX,mucinex.co.nz
DOMAIN-SUFFIX,mucinex.com.cn
