# mudvod
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mudvod.list | 规则数: 10
DOMAIN-SUFFIX,biggggg.com
DOMAIN-SUFFIX,mudvod.tv
DOMAIN-SUFFIX,nbys.tv
DOMAIN-SUFFIX,nbys1.tv
DOMAIN-SUFFIX,nbyy.tv
DOMAIN-SUFFIX,newpppp.com
DOMAIN-SUFFIX,nivod.tv
DOMAIN-SUFFIX,nivodi.tv
DOMAIN-SUFFIX,nivodz.com
DOMAIN-SUFFIX,vod360.net
