# muji
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/muji.list | 规则数: 8
DOMAIN-SUFFIX,muji.com
DOMAIN-SUFFIX,muji.eu
DOMAIN-SUFFIX,muji.net
DOMAIN-SUFFIX,muji.tw
DOMAIN-SUFFIX,muji.us
DOMAIN-SUFFIX,mujikorea.net
DOMAIN-SUFFIX,muji.com.hk
DOMAIN-SUFFIX,muji.com.cn
