# mxroute
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/mxroute.list | 规则数: 5
DOMAIN-SUFFIX,mxlogin.com
DOMAIN-SUFFIX,mxroute.com
DOMAIN-SUFFIX,mxroutedocs.com
DOMAIN-SUFFIX,mxroutehelp.com
DOMAIN-SUFFIX,mxrouting.net
