# niconico
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/niconico.list | 规则数: 10
DOMAIN-SUFFIX,nico
DOMAIN-SUFFIX,nico.ms
DOMAIN-SUFFIX,nicochannel.jp
DOMAIN-SUFFIX,nicodic.jp
DOMAIN-SUFFIX,nicomanga.jp
DOMAIN-SUFFIX,niconico.com
DOMAIN-SUFFIX,nicoseiga.jp
DOMAIN-SUFFIX,nicovideo.jp
DOMAIN-SUFFIX,nimg.jp
DOMAIN-SUFFIX,simg.jp
