# notion
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/notion.list | 规则数: 7
DOMAIN-SUFFIX,notion-static.com
DOMAIN-SUFFIX,notion-status.com
DOMAIN-SUFFIX,notion.com
DOMAIN-SUFFIX,notion.new
DOMAIN-SUFFIX,notion.site
DOMAIN-SUFFIX,notion.so
DOMAIN-SUFFIX,notionusercontent.com
