# nvidia@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/nvidia@cn.list | 规则数: 4
DOMAIN-SUFFIX,geforce.cn
DOMAIN-SUFFIX,gputechconf.cn
DOMAIN-SUFFIX,nvidia.cn
DOMAIN,cn.download.nvidia.com
