# ok
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ok.list | 规则数: 19
DOMAIN,st-ok-pts.cdn-vk.ru
DOMAIN,st-ok.cdn-vk.ru
DOMAIN-SUFFIX,odnoklassniki.eu
DOMAIN-SUFFIX,odnoklassniki.lv
DOMAIN-SUFFIX,odkl.ru
DOMAIN-SUFFIX,odnoklasniki.by
DOMAIN-SUFFIX,odnoklasniki.ua
DOMAIN-SUFFIX,odnoklassniki.am
DOMAIN-SUFFIX,odnoklassniki.by
DOMAIN-SUFFIX,okcdn.ru
DOMAIN-SUFFIX,insideok.ru
DOMAIN-SUFFIX,odnoklassniki.ru
DOMAIN-SUFFIX,apiok.ru
DOMAIN-SUFFIX,odnoklassniki.tj
DOMAIN-SUFFIX,ok.me
DOMAIN-SUFFIX,ok.ru
DOMAIN-SUFFIX,okl.lt
DOMAIN-SUFFIX,oktech.ru
DOMAIN-SUFFIX,odnoklassniki.co.ee
