# okaapps
# 由 fly-rule 自 metacubex@cb3e075 转换，请勿手工编辑
# 上游: geo/geosite/classical/okaapps.list | 规则数: 1
# 跳过 Surge 不支持的 DOMAIN-REGEX 1 条，例: 'DOMAIN-REGEX,^(.+\\.)*zh\\.okaapps\\.com$'
DOMAIN-SUFFIX,okaapps.com
