# okx
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/okx.list | 规则数: 10
DOMAIN-SUFFIX,okex.com
DOMAIN-SUFFIX,okx-dns.com
DOMAIN-SUFFIX,okx-dns1.com
DOMAIN-SUFFIX,okx-dns2.com
DOMAIN-SUFFIX,okx.ac
DOMAIN-SUFFIX,okx.cab
DOMAIN-SUFFIX,okx.com
DOMAIN-SUFFIX,xlayer.tech
DOMAIN-SUFFIX,okx.com.cdn.cloudflare.net
DOMAIN-SUFFIX,oklink.com
