# olevod
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/olevod.list | 规则数: 9
DOMAIN-SUFFIX,haiwaikan.com
DOMAIN-SUFFIX,iole.tv
DOMAIN-SUFFIX,olehd.com
DOMAIN-SUFFIX,olelive.com
DOMAIN-SUFFIX,olevod.com
DOMAIN-SUFFIX,olevod.io
DOMAIN-SUFFIX,olevod.tv
DOMAIN-SUFFIX,olevodtv.com
DOMAIN-SUFFIX,olemovienews.com
