# openstreetmap
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/openstreetmap.list | 规则数: 9
DOMAIN-SUFFIX,openmaps.org
DOMAIN-SUFFIX,openstreetmap.com
DOMAIN-SUFFIX,openstreetmap.net
DOMAIN-SUFFIX,openstreetmap.org
DOMAIN-SUFFIX,openstreetmaps.org
DOMAIN-SUFFIX,osm.org
DOMAIN-SUFFIX,osmfoundation.org
DOMAIN-SUFFIX,stateofthemap.com
DOMAIN-SUFFIX,stateofthemap.org
