# openjsfoundation
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/openjsfoundation.list | 规则数: 13
DOMAIN,amp.akamaized.net
DOMAIN-SUFFIX,openjsf.org
DOMAIN-SUFFIX,amp.dev
DOMAIN-SUFFIX,ampproject.com
DOMAIN-SUFFIX,ampproject.net
DOMAIN-SUFFIX,ampproject.org
DOMAIN-SUFFIX,electronjs.org
DOMAIN-SUFFIX,jquery.com
DOMAIN-SUFFIX,jquerymobile.com
DOMAIN-SUFFIX,jqueryui.com
DOMAIN-SUFFIX,mochajs.org
DOMAIN-SUFFIX,nodejs.org
DOMAIN,cdn.ampproject.org
