# origin
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/origin.list | 规则数: 9
DOMAIN,cloudsync-prod.s3.amazonaws.com
DOMAIN,origin-a.akamaihd.net
DOMAIN,rtm.tnt-ea.com
DOMAIN,ssl-lvlt.cdn.ea.com
DOMAIN-SUFFIX,dawngate.com
DOMAIN-SUFFIX,eastore.com
DOMAIN-SUFFIX,lordofultima.com
DOMAIN-SUFFIX,origin.com
DOMAIN-SUFFIX,origin.tv
