# ozon@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ozon@ads.list | 规则数: 18
DOMAIN,ad.ozone.ru
DOMAIN,adv.ozon.ru
DOMAIN,agency-adv.ozon.ru
DOMAIN,analytics-adv.ozon.ru
DOMAIN,beginners-adv.ozon.ru
DOMAIN,google-analytics-suite.ozon.ru
DOMAIN,loyalnost-adv.ozon.ru
DOMAIN,new-adv.ozon.ru
DOMAIN,prodvizhenie-adv.ozon.ru
DOMAIN,questions-adv.ozon.ru
DOMAIN,sentry.ozon.ru
DOMAIN,xapi.ozon.by
DOMAIN,xapi.ozon.com
DOMAIN,xapi.ozon.com.by
DOMAIN,xapi.ozon.com.kz
DOMAIN,xapi.ozon.kz
DOMAIN,xapi.ozon.ru
DOMAIN,xapi.ozonru.me
