# panasonic
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/panasonic.list | 规则数: 5
DOMAIN-SUFFIX,panasonic
DOMAIN-SUFFIX,panasonic.com
DOMAIN-SUFFIX,panasonic.jp
DOMAIN-SUFFIX,technics.com
DOMAIN-SUFFIX,panasonic.cn
