# patreon
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/patreon.list | 规则数: 4
DOMAIN,live-patreon-marketing.pantheonsite.io
DOMAIN-SUFFIX,patreon.com
DOMAIN-SUFFIX,patreoncommunity.com
DOMAIN-SUFFIX,patreonusercontent.com
