# perl
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/perl.list | 规则数: 5
DOMAIN-SUFFIX,perl.org
DOMAIN-SUFFIX,cpan.org
DOMAIN-SUFFIX,metacpan.org
DOMAIN-SUFFIX,modperl.pl
DOMAIN-SUFFIX,perl.apache.org
