# perplexity
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/perplexity.list | 规则数: 5
DOMAIN,ppl-ai-file-upload.s3.amazonaws.com
DOMAIN,pplx-res.cloudinary.com
DOMAIN-SUFFIX,perplexity.ai
DOMAIN-SUFFIX,perplexity.com
DOMAIN-SUFFIX,pplx.ai
