# picsee
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/picsee.list | 规则数: 6
DOMAIN-SUFFIX,pics.ee
DOMAIN-SUFFIX,picsee.co
DOMAIN-SUFFIX,picsee.pro
DOMAIN-SUFFIX,pise.pw
DOMAIN-SUFFIX,pros.ee
DOMAIN-SUFFIX,pse.is
