# polyu
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/polyu.list | 规则数: 5
DOMAIN-SUFFIX,polyu.hk
DOMAIN-SUFFIX,polyu.edu.hk
DOMAIN-SUFFIX,cpce-polyu.edu.hk
DOMAIN-SUFFIX,speed-polyu.edu.hk
DOMAIN-SUFFIX,hkcc-polyu.edu.hk
