# pornhub
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/pornhub.list | 规则数: 9
DOMAIN-SUFFIX,gaytube.com
DOMAIN-SUFFIX,phncdn.com
DOMAIN-SUFFIX,phprcdn.com
DOMAIN-SUFFIX,porngub.com
DOMAIN-SUFFIX,pornhub-deutsch.net
DOMAIN-SUFFIX,pornhubapparel.com
DOMAIN-SUFFIX,pornhub.com
DOMAIN-SUFFIX,pornhub.org
DOMAIN-SUFFIX,pornhubpremium.com
