# protonmail
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/protonmail.list | 规则数: 9
DOMAIN-SUFFIX,pm.me
DOMAIN-SUFFIX,proton.me
DOMAIN-SUFFIX,protonmail.ch
DOMAIN-SUFFIX,protonmail.com
DOMAIN-SUFFIX,protonstatus.com
DOMAIN-SUFFIX,protontech.ch
DOMAIN-SUFFIX,protonvpn.ch
DOMAIN-SUFFIX,protonvpn.com
DOMAIN-SUFFIX,protonweb.com
