# purikonejp
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/purikonejp.list | 规则数: 4
DOMAIN,prd-priconne-redive.akamaized.net
DOMAIN-SUFFIX,priconne-redive.jp
DOMAIN-SUFFIX,api-priconne-redive.cygames.jp
DOMAIN-SUFFIX,omotenashi.cygames.jp
