# qianxin
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/qianxin.list | 规则数: 7
DOMAIN-SUFFIX,95015.com
DOMAIN-SUFFIX,qianxin.com
DOMAIN-SUFFIX,qianxincdn.com
DOMAIN-SUFFIX,seclab.online
DOMAIN-SUFFIX,tianshucup.com
DOMAIN-SUFFIX,ceati.org.cn
DOMAIN-SUFFIX,datacon.org.cn
