# qingcloud
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/qingcloud.list | 规则数: 6
DOMAIN-SUFFIX,frontwize.com
DOMAIN-SUFFIX,qingcache.com
DOMAIN-SUFFIX,qingcloud.com
DOMAIN-SUFFIX,qingstor.com
DOMAIN-SUFFIX,routewize.com
DOMAIN-SUFFIX,yunify.com
