# qiniu
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/qiniu.list | 规则数: 10
DOMAIN-SUFFIX,qbox.me
DOMAIN-SUFFIX,qiniu.com
DOMAIN-SUFFIX,qiniucdn.com
DOMAIN-SUFFIX,qiniudn.com
DOMAIN-SUFFIX,qiniudns.com
DOMAIN-SUFFIX,qiniup.com
DOMAIN-SUFFIX,qnsdk.com
DOMAIN-SUFFIX,qnssl.com
DOMAIN-SUFFIX,staticfile.net
DOMAIN-SUFFIX,staticfile.org
