# qnap@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/qnap@cn.list | 规则数: 4
DOMAIN-SUFFIX,mycloudnas.com
DOMAIN-SUFFIX,myqnapcloud.cn
DOMAIN-SUFFIX,qlinkto.cn
DOMAIN-SUFFIX,qnap.com.cn
