# qualcomm@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/qualcomm@cn.list | 规则数: 6
DOMAIN-SUFFIX,gpsonextra.net
DOMAIN-SUFFIX,izatcloud.net
DOMAIN-SUFFIX,qceventscenter.com.cn
DOMAIN-SUFFIX,qualcomm.cn
DOMAIN-SUFFIX,qualcomm.cn.cdn.cloudflare.net
DOMAIN-SUFFIX,xtracloud.cn
