# razer
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/razer.list | 规则数: 9
DOMAIN-SUFFIX,razer.com
DOMAIN-SUFFIX,razerofficial.com
DOMAIN-SUFFIX,razersupport.com
DOMAIN-SUFFIX,razerzone.jp
DOMAIN-SUFFIX,respawnbyrazer.com
DOMAIN-SUFFIX,rzr.to
DOMAIN-SUFFIX,razerapi.com
DOMAIN-SUFFIX,razersynapse.com
DOMAIN-SUFFIX,razerzone.com
