# readthedocs
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/readthedocs.list | 规则数: 4
DOMAIN-SUFFIX,readthedocs-hosted.com
DOMAIN-SUFFIX,readthedocs.com
DOMAIN-SUFFIX,readthedocs.io
DOMAIN-SUFFIX,readthedocs.org
