# reddit
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/reddit.list | 规则数: 12
DOMAIN-SUFFIX,redd.it
DOMAIN-SUFFIX,reddit.com
DOMAIN-SUFFIX,redditblog.com
DOMAIN-SUFFIX,reddithelp.com
DOMAIN-SUFFIX,redditinc.com
DOMAIN-SUFFIX,redditmail.com
DOMAIN-SUFFIX,redditmedia.com
DOMAIN-SUFFIX,redditspace.com
DOMAIN-SUFFIX,redditstatic.com
DOMAIN-SUFFIX,redditstatus.com
DOMAIN-SUFFIX,reddit.app.link
DOMAIN-SUFFIX,reddit.map.fastly.net
