# redtube
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/redtube.list | 规则数: 5
DOMAIN-SUFFIX,livehdcams.com
DOMAIN-SUFFIX,redtube.com
DOMAIN-SUFFIX,redtubepremium.com
DOMAIN-SUFFIX,rdtcdn.com
DOMAIN-SUFFIX,redtube.com.br
