# roku
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/roku.list | 规则数: 6
DOMAIN-SUFFIX,fandango.com
DOMAIN-SUFFIX,mgo.com
DOMAIN-SUFFIX,mgo-images.com
DOMAIN-SUFFIX,ravm.tv
DOMAIN-SUFFIX,roku.com
DOMAIN-SUFFIX,rokutime.com
