# schwab
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/schwab.list | 规则数: 7
DOMAIN-SUFFIX,aboutschwab.com
DOMAIN-SUFFIX,schwab.com
DOMAIN-SUFFIX,schwabassetmanagement.com
DOMAIN-SUFFIX,schwabplan.com
DOMAIN-SUFFIX,schwab.co.uk
DOMAIN-SUFFIX,schwab.com.hk
DOMAIN-SUFFIX,schwab.com.sg
