# sharepoint
# 由 fly-rule 自 metacubex@dad2963 转换，请勿手工编辑
# 上游: geo/geosite/classical/sharepoint.list | 规则数: 3
DOMAIN-SUFFIX,sharepoint.cn
DOMAIN-SUFFIX,sharepoint.com
DOMAIN-SUFFIX,sharepointonline.com
