# shopify
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/shopify.list | 规则数: 8
DOMAIN-SUFFIX,myshopify.com
DOMAIN-SUFFIX,shop.app
DOMAIN-SUFFIX,shopify.com
DOMAIN-SUFFIX,shopify.dev
DOMAIN-SUFFIX,shopifycdn.com
DOMAIN-SUFFIX,shopifycloud.com
DOMAIN-SUFFIX,shopifystatus.com
DOMAIN-SUFFIX,shopifysvc.com
