# shuqi
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/shuqi.list | 规则数: 11
DOMAIN-SUFFIX,11222.cn
DOMAIN-SUFFIX,aliwx.net
DOMAIN-SUFFIX,ishuqi.com
DOMAIN-SUFFIX,newstjk.com
DOMAIN-SUFFIX,shuqi.com
DOMAIN-SUFFIX,shuqiapi.com
DOMAIN-SUFFIX,shuqiread.com
DOMAIN-SUFFIX,shuqireader.com
DOMAIN-SUFFIX,shuqistat.com
DOMAIN-SUFFIX,sqreader.com
DOMAIN-SUFFIX,aliwx.com.cn
