# sina@!cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/sina@!cn.list | 规则数: 7
DOMAIN-SUFFIX,hk.weibo.com
DOMAIN-SUFFIX,my.weibo.com
DOMAIN-SUFFIX,overseas.weibo.com
DOMAIN-SUFFIX,sg.weibo.com
DOMAIN-SUFFIX,th.weibo.com
DOMAIN-SUFFIX,tw.weibo.com
DOMAIN-SUFFIX,us.weibo.com
