# skyperfect
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/skyperfect.list | 规则数: 7
DOMAIN-SUFFIX,skyperfectjsat.space
DOMAIN-SUFFIX,sptvbroadcast.com
DOMAIN-SUFFIX,spcc-sp.com
DOMAIN-SUFFIX,hominis.media
DOMAIN-SUFFIX,jsati.com
DOMAIN-SUFFIX,jsatmobile.com
DOMAIN-SUFFIX,skyperfectv.co.jp
