# slack
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/slack.list | 规则数: 11
DOMAIN-SUFFIX,slack-core.com
DOMAIN-SUFFIX,slack-edge.com
DOMAIN-SUFFIX,slack-files.com
DOMAIN-SUFFIX,slack-imgs.com
DOMAIN-SUFFIX,slack-msgs.com
DOMAIN-SUFFIX,slack-redir.net
DOMAIN-SUFFIX,slack.com
DOMAIN-SUFFIX,slackb.com
DOMAIN-SUFFIX,slackcertified.com
DOMAIN-SUFFIX,slackdemo.com
DOMAIN-SUFFIX,slackhq.com
