# sling
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/sling.list | 规则数: 5
DOMAIN-SUFFIX,dishworld.com
DOMAIN-SUFFIX,slinginternational.com
DOMAIN-SUFFIX,sling.com
DOMAIN-SUFFIX,movenetworks.com
DOMAIN-SUFFIX,movetv.com
