# snap
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/snap.list | 规则数: 9
DOMAIN,impala-media-production.s3.amazonaws.com
DOMAIN-SUFFIX,sc-cdn.net
DOMAIN-SUFFIX,sc-gw.com
DOMAIN-SUFFIX,sc-static.net
DOMAIN-SUFFIX,snap-dev.net
DOMAIN-SUFFIX,snap.com
DOMAIN-SUFFIX,snapchat.com
DOMAIN-SUFFIX,snapkit.co
DOMAIN-SUFFIX,snapads.com
