# sonemic
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/sonemic.list | 规则数: 6
DOMAIN-SUFFIX,glitchwave.com
DOMAIN-SUFFIX,rateyourmusic.com
DOMAIN-SUFFIX,rym.fm
DOMAIN-SUFFIX,snmc.io
DOMAIN-SUFFIX,sonematic.net
DOMAIN-SUFFIX,sonemic.com
