# spotify@ads
# 由 fly-rule 自 metacubex@dad2963 转换，请勿手工编辑
# 上游: geo/geosite/classical/spotify@ads.list | 规则数: 3
DOMAIN,adeventtracker.spotify.com
DOMAIN,adstudio-assets.scdn.co
DOMAIN,bloodhound.spotify.com
