# squareup
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/squareup.list | 规则数: 12
DOMAIN-SUFFIX,cash.app
DOMAIN-SUFFIX,cashbycashapp.com
DOMAIN-SUFFIX,gosq.co
DOMAIN-SUFFIX,gosq.com
DOMAIN-SUFFIX,issquaredown.com
DOMAIN-SUFFIX,issquareup.com
DOMAIN-SUFFIX,mkt.com
DOMAIN-SUFFIX,sellercommunity.com
DOMAIN-SUFFIX,squarecapital.com
DOMAIN-SUFFIX,squarecdn.com
DOMAIN-SUFFIX,squarecloudservices.com
DOMAIN-SUFFIX,squareup.com
