# starplus
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/starplus.list | 规则数: 6
DOMAIN-SUFFIX,starott.com
DOMAIN-SUFFIX,starplus.com
DOMAIN-SUFFIX,star.api.edge.bamgrid.com
DOMAIN-SUFFIX,star.connections.edge.bamgrid.com
DOMAIN-SUFFIX,star.content.edge.bamgrid.com
DOMAIN-SUFFIX,star.playback.edge.bamgrid.com
