# sto-express
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/sto-express.list | 规则数: 6
DOMAIN-SUFFIX,sto-express.cn
DOMAIN-SUFFIX,sto-express.com
DOMAIN-SUFFIX,sto.cn
DOMAIN-SUFFIX,stointl.com
DOMAIN-SUFFIX,stosolution.com
DOMAIN-SUFFIX,sto-express.com.cn
