# strikingly
# 由 fly-rule 自 metacubex@dad2963 转换，请勿手工编辑
# 上游: geo/geosite/classical/strikingly.list | 规则数: 3
DOMAIN-SUFFIX,mystrikingly.com
DOMAIN-SUFFIX,strikingly.com
DOMAIN-SUFFIX,strikinglycdn.com
