# suishouji
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/suishouji.list | 规则数: 5
DOMAIN-SUFFIX,feidee.cn
DOMAIN-SUFFIX,feidee.com
DOMAIN-SUFFIX,feidee.net
DOMAIN-SUFFIX,ssjlicai.com
DOMAIN-SUFFIX,sui.com
