# symantec-pki
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/symantec-pki.list | 规则数: 5
DOMAIN-SUFFIX,symauth.com
DOMAIN-SUFFIX,symcb.com
DOMAIN-SUFFIX,symcd.com
DOMAIN-SUFFIX,pki.symantec.com
DOMAIN-SUFFIX,ws.symantec.com
