# taikang
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/taikang.list | 规则数: 4
DOMAIN-SUFFIX,taikang.com
DOMAIN-SUFFIX,taikanglife.com
DOMAIN-SUFFIX,taikangzhijia.com
DOMAIN-SUFFIX,tkhealthcare.com
