# tcl
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/tcl.list | 规则数: 12
DOMAIN-SUFFIX,tclai.top
DOMAIN-SUFFIX,tcl.com
DOMAIN-SUFFIX,tcltech.com
DOMAIN-SUFFIX,leiniao.com
DOMAIN-SUFFIX,my7v.com
DOMAIN-SUFFIX,tcl.com.cn
DOMAIN-SUFFIX,ads-uo.api.leiniao.com
DOMAIN-SUFFIX,ads-ut.api.leiniao.com
DOMAIN-SUFFIX,ads.api.my7v.com
DOMAIN-SUFFIX,euads-o.api.leiniao.com
DOMAIN-SUFFIX,hwads-t.api.my7v.com
DOMAIN-SUFFIX,testads.api.my7v.com
