# technogym
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/technogym.list | 规则数: 8
DOMAIN-SUFFIX,letsmoveforabetterworld.com
DOMAIN-SUFFIX,technogym.bg
DOMAIN-SUFFIX,technogym.ch
DOMAIN-SUFFIX,technogym.com
DOMAIN-SUFFIX,technogym.ru
DOMAIN-SUFFIX,technogym.su
DOMAIN-SUFFIX,wellnessinstitute.com
DOMAIN-SUFFIX,technogym.com.br
