# tesla
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/tesla.list | 规则数: 11
DOMAIN-SUFFIX,solarcity.com
DOMAIN-SUFFIX,tesla.com
DOMAIN-SUFFIX,tesla.services
DOMAIN-SUFFIX,teslaenergy.services
DOMAIN-SUFFIX,teslamotors.com
DOMAIN-SUFFIX,teslazta.net
DOMAIN-SUFFIX,ts.la
DOMAIN-SUFFIX,tesla.cn
DOMAIN-SUFFIX,tesla.com.cn
DOMAIN-SUFFIX,teslamotors.cn
DOMAIN-SUFFIX,teslamotors.com.cn
