# thesun
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/thesun.list | 规则数: 7
DOMAIN-SUFFIX,dreamteamfc.com
DOMAIN-SUFFIX,page3.com
DOMAIN-SUFFIX,talksport.com
DOMAIN-SUFFIX,thesun.ie
DOMAIN-SUFFIX,sunbingo.co.uk
DOMAIN-SUFFIX,thescottishsun.co.uk
DOMAIN-SUFFIX,thesun.co.uk
