# tilda
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/tilda.list | 规则数: 6
DOMAIN-SUFFIX,tilda.cc
DOMAIN-SUFFIX,tilda.ru
DOMAIN-SUFFIX,tilda.ws
DOMAIN-SUFFIX,tildaapi.com
DOMAIN-SUFFIX,tildacdn.com
DOMAIN-SUFFIX,tildacdn.net
