# tmdb
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/tmdb.list | 规则数: 4
DOMAIN,tmdb-image-prod.b-cdn.net
DOMAIN,tmdb-web-image-prod.b-cdn.net
DOMAIN-SUFFIX,themoviedb.org
DOMAIN-SUFFIX,tmdb.org
