# trae
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/trae.list | 规则数: 12
DOMAIN-SUFFIX,doudou.com
DOMAIN-SUFFIX,marscode.cn
DOMAIN-SUFFIX,mcbaas.work
DOMAIN-SUFFIX,mcdemo.show
DOMAIN-SUFFIX,mchost.guru
DOMAIN-SUFFIX,mcprev.cn
DOMAIN-SUFFIX,tcwqqdy.guru
DOMAIN-SUFFIX,trae.cn
DOMAIN-SUFFIX,trae.guru
DOMAIN-SUFFIX,yoma.cn
DOMAIN-SUFFIX,marscode.com.cn
DOMAIN-SUFFIX,trae.com.cn
