# tutanota
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/tutanota.list | 规则数: 6
DOMAIN-SUFFIX,keemail.me
DOMAIN-SUFFIX,tuta.com
DOMAIN-SUFFIX,tuta.io
DOMAIN-SUFFIX,tutamail.com
DOMAIN-SUFFIX,tutanota.com
DOMAIN-SUFFIX,tutanota.de
