# uc
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/uc.list | 规则数: 9
DOMAIN-SUFFIX,open-uc.cn
DOMAIN-SUFFIX,uc-engine.cn
DOMAIN-SUFFIX,uc.cn
DOMAIN-SUFFIX,uc123.com
DOMAIN-SUFFIX,ucfly.com
DOMAIN-SUFFIX,ucweb.com
DOMAIN-SUFFIX,uczzd.cn
DOMAIN-SUFFIX,ads.uc.cn
DOMAIN-SUFFIX,adslot.uc.cn
