# upai
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/upai.list | 规则数: 6
DOMAIN-SUFFIX,aicdn.com
DOMAIN-SUFFIX,upai.com
DOMAIN-SUFFIX,upaiyun.com
DOMAIN-SUFFIX,upcdn.net
DOMAIN-SUFFIX,upyun.com
DOMAIN-SUFFIX,oncdp.com
