# visa@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/visa@cn.list | 规则数: 9
DOMAIN-SUFFIX,visa.cn
DOMAIN-SUFFIX,visa.com.cn
DOMAIN-SUFFIX,financialsoccer.com.cn
DOMAIN-SUFFIX,practicalmoneyskills.cn
DOMAIN-SUFFIX,practicalmoneyskills.com.cn
DOMAIN-SUFFIX,visainfinite.cn
DOMAIN-SUFFIX,visapay.cn
DOMAIN-SUFFIX,visaplatinum.cn
DOMAIN-SUFFIX,visaplatinum.com.cn
