# visualarts
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/visualarts.list | 规则数: 14
DOMAIN-SUFFIX,kamisama-day.jp
DOMAIN-SUFFIX,kamisama-maeda-lab.com
DOMAIN-SUFFIX,anigema.jp
DOMAIN-SUFFIX,charlotte-anime.jp
DOMAIN-SUFFIX,clannad-movie.jp
DOMAIN-SUFFIX,heaven-burns-red.com
DOMAIN-SUFFIX,koubaibu.jp
DOMAIN-SUFFIX,abow.jp
DOMAIN-SUFFIX,angelbeats.jp
DOMAIN-SUFFIX,litbus-anime.com
DOMAIN-SUFFIX,visual-arts.jp
DOMAIN-SUFFIX,rewrite-anime.tv
DOMAIN-SUFFIX,visualarts.gr.jp
DOMAIN-SUFFIX,product.co.jp
