# vivo
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/vivo.list | 规则数: 8
DOMAIN-SUFFIX,budingscan.com
DOMAIN-SUFFIX,iqoo.com
DOMAIN-SUFFIX,vivo.cn
DOMAIN-SUFFIX,vivo.com
DOMAIN-SUFFIX,vvstc.com
DOMAIN-SUFFIX,blueos.com.cn
DOMAIN-SUFFIX,vivo.com.cn
DOMAIN-SUFFIX,vivoglobal.com
