# vodafone
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/vodafone.list | 规则数: 9
DOMAIN-SUFFIX,vodafone.com
DOMAIN-SUFFIX,vodafone.de
DOMAIN-SUFFIX,vodafone.it
DOMAIN-SUFFIX,vodafone.nl
DOMAIN-SUFFIX,myvodafone.com.au
DOMAIN-SUFFIX,myvodafone.com.ws
DOMAIN-SUFFIX,vodafone.co.uk
DOMAIN-SUFFIX,vodafone.com.au
DOMAIN-SUFFIX,vodafone.com.tr
