# volvo@cn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/volvo@cn.list | 规则数: 6
DOMAIN-SUFFIX,vfsco.com.cn
DOMAIN-SUFFIX,volvo.cn
DOMAIN-SUFFIX,volvo.com.cn
DOMAIN-SUFFIX,volvogroup.cn
DOMAIN-SUFFIX,volvogroup.com.cn
DOMAIN-SUFFIX,volvotrucks.com.cn
