# wbgames
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/wbgames.list | 规则数: 6
DOMAIN,datarouter.apps.netherrealm.com
DOMAIN,wb-agora-hydra-file-storage-k1.s3.amazonaws.com
DOMAIN-SUFFIX,warnerbrosgames.com
DOMAIN-SUFFIX,wbagora.com
DOMAIN-SUFFIX,wbgames.com
DOMAIN-SUFFIX,wbinsights.com
