# weathercn
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/weathercn.list | 规则数: 5
DOMAIN-SUFFIX,hf-aw.cn
DOMAIN-SUFFIX,hf-aw.com
DOMAIN-SUFFIX,huafeng-accuweather.cn
DOMAIN-SUFFIX,huafengaw.com
DOMAIN-SUFFIX,weathercn.com
