# wholefoodsmarket
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/wholefoodsmarket.list | 规则数: 7
DOMAIN-SUFFIX,wfm.com
DOMAIN-SUFFIX,wholecitiesfoundation.org
DOMAIN-SUFFIX,wholefoods.com
DOMAIN-SUFFIX,wholefoodsmarket.com
DOMAIN-SUFFIX,wholekidsfoundation.org
DOMAIN-SUFFIX,wholeplanetfoundation.org
DOMAIN-SUFFIX,wholefoodsmarket.co.uk
