# wikimedia
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/wikimedia.list | 规则数: 18
DOMAIN-SUFFIX,mediawiki.org
DOMAIN-SUFFIX,wikibooks.org
DOMAIN-SUFFIX,wikidata.org
DOMAIN-SUFFIX,wikimediafoundation.org
DOMAIN-SUFFIX,wikimedia.org
DOMAIN-SUFFIX,wikinews.org
DOMAIN-SUFFIX,wikipedia.org
DOMAIN-SUFFIX,wikiquote.org
DOMAIN-SUFFIX,wikisource.org
DOMAIN-SUFFIX,wikiversity.org
DOMAIN-SUFFIX,wikivoyage.org
DOMAIN-SUFFIX,wiktionary.org
DOMAIN-SUFFIX,wmfusercontent.org
DOMAIN-SUFFIX,w.wiki
DOMAIN-SUFFIX,toolforge.org
DOMAIN-SUFFIX,wikimediacloud.org
DOMAIN-SUFFIX,wmcloud.org
DOMAIN-SUFFIX,wmflabs.org
