# wix
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/wix.list | 规则数: 9
DOMAIN-SUFFIX,editorx.com
DOMAIN-SUFFIX,parastorage.com
DOMAIN-SUFFIX,wix-code.com
DOMAIN-SUFFIX,wix.com
DOMAIN-SUFFIX,wixanswers.com
DOMAIN-SUFFIX,wixapps.net
DOMAIN-SUFFIX,wixmp.com
DOMAIN-SUFFIX,wixsite.com
DOMAIN-SUFFIX,wixstatic.com
