# wordpress
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/wordpress.list | 规则数: 10
DOMAIN-SUFFIX,videopress.com
DOMAIN-SUFFIX,w.org
DOMAIN-SUFFIX,wordcamp.org
DOMAIN-SUFFIX,wordpress.com
DOMAIN-SUFFIX,wordpress.net
DOMAIN-SUFFIX,wordpress.org
DOMAIN-SUFFIX,wordpress.tv
DOMAIN-SUFFIX,wp-themes.com
DOMAIN-SUFFIX,wp.com
DOMAIN-SUFFIX,wpvip.com
