# xiaoyuzhou
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/xiaoyuzhou.list | 规则数: 5
DOMAIN-SUFFIX,xyzfm.space
DOMAIN-SUFFIX,xyzfm.link
DOMAIN-SUFFIX,xyzcdn.net
DOMAIN-SUFFIX,xiaoyuzhoufm.com
DOMAIN-SUFFIX,podcast.xyz
