# xiaohongshu
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/xiaohongshu.list | 规则数: 12
DOMAIN-SUFFIX,redelight.cn
DOMAIN-SUFFIX,rnote.com
DOMAIN-SUFFIX,xhscdn.com
DOMAIN-SUFFIX,xhscdn.net
DOMAIN-SUFFIX,xhslink.com
DOMAIN-SUFFIX,xhsrcdn.com
DOMAIN-SUFFIX,xiaohongshu.com
DOMAIN-SUFFIX,askdiandian.com
DOMAIN-SUFFIX,diandianlife.top
DOMAIN-SUFFIX,rednote.com
DOMAIN-SUFFIX,rednote.com.my
DOMAIN-SUFFIX,rednotecdn.com
