# xiaoheihe
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/xiaoheihe.list | 规则数: 8
DOMAIN-SUFFIX,1xhh.cn
DOMAIN-SUFFIX,accxiaoheihe.com
DOMAIN-SUFFIX,chat.top
DOMAIN-SUFFIX,debugmode.cn
DOMAIN-SUFFIX,max-c.com
DOMAIN-SUFFIX,maxadmin.cn
DOMAIN-SUFFIX,maxjia.com
DOMAIN-SUFFIX,xiaoheihe.cn
