# ximalaya@ads
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/ximalaya@ads.list | 规则数: 3
DOMAIN-SUFFIX,adbehavior.ximalaya.com
DOMAIN-SUFFIX,adse.wsa.ximalaya.com
DOMAIN-SUFFIX,adse.ximalaya.com
