# xueersi
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/xueersi.list | 规则数: 12
DOMAIN-SUFFIX,100tal.com
DOMAIN-SUFFIX,aoshu.com
DOMAIN-SUFFIX,eduu.com
DOMAIN-SUFFIX,eduuu.com
DOMAIN-SUFFIX,gaokao.com
DOMAIN-SUFFIX,speiyou.com
DOMAIN-SUFFIX,tal.com
DOMAIN-SUFFIX,xesimg.com
DOMAIN-SUFFIX,xueersi.com
DOMAIN-SUFFIX,youjiao.com
DOMAIN-SUFFIX,zhongkao.com
DOMAIN-SUFFIX,zuowen.com
