# xvideos
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/xvideos.list | 规则数: 5
DOMAIN-SUFFIX,xv-ru.com
DOMAIN-SUFFIX,xvideos-ar.com
DOMAIN-SUFFIX,xvideos-cdn.com
DOMAIN-SUFFIX,xvideos-india.com
DOMAIN-SUFFIX,xvideos.com
