# yokaverse
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/yokaverse.list | 规则数: 7
DOMAIN-SUFFIX,dobest.com
DOMAIN-SUFFIX,langrenclub.com
DOMAIN-SUFFIX,sanguosha.com
DOMAIN-SUFFIX,xhlsgs.com
DOMAIN-SUFFIX,xinwuji.com
DOMAIN-SUFFIX,yokaverse.com
DOMAIN-SUFFIX,zhuoyou.com
