# yostar
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/yostar.list | 规则数: 9
DOMAIN-SUFFIX,yo-star.com
DOMAIN-SUFFIX,yostar.net
DOMAIN-SUFFIX,yostarplat.com
DOMAIN-SUFFIX,stargazer-games.com
DOMAIN-SUFFIX,stellasora.global
DOMAIN-SUFFIX,stellasora.jp
DOMAIN-SUFFIX,yostar.co.jp
DOMAIN-SUFFIX,yostar-pictures.co.jp
DOMAIN-SUFFIX,yostar.cn
