# yunlaopo
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/yunlaopo.list | 规则数: 6
DOMAIN-SUFFIX,doure.net
DOMAIN-SUFFIX,kuaipa.net
DOMAIN-SUFFIX,miaopa.net
DOMAIN-SUFFIX,yunlaopo.cc
DOMAIN-SUFFIX,yunlaopo.com
DOMAIN-SUFFIX,yunlaopo.net
