# zendesk
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zendesk.list | 规则数: 6
DOMAIN-SUFFIX,outbound.io
DOMAIN-SUFFIX,zdassets.com
DOMAIN-SUFFIX,zdusercontent.com
DOMAIN-SUFFIX,zendesk.com
DOMAIN-SUFFIX,zndsk.com
DOMAIN-SUFFIX,zopim.com
