# zhangtao
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zhangtao.list | 规则数: 8
DOMAIN-SUFFIX,mob.com
DOMAIN-SUFFIX,sharesdk.cn
DOMAIN-SUFFIX,accuratead.cn
DOMAIN-SUFFIX,dutils.com
DOMAIN-SUFFIX,hiaiabc.com
DOMAIN-SUFFIX,mobsdks.com
DOMAIN-SUFFIX,tec73.com
DOMAIN-SUFFIX,yksdks.com
