# zhihu
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zhihu.list | 规则数: 6
DOMAIN-SUFFIX,zhihu.com
DOMAIN-SUFFIX,zhimg.com
DOMAIN-SUFFIX,laiyagushi.com
DOMAIN-SUFFIX,vzuu.com
DOMAIN-SUFFIX,crash2.zhihu.com
DOMAIN-SUFFIX,zhihu-web-analytics.zhihu.com
