# zhimeishe
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zhimeishe.list | 规则数: 5
DOMAIN-SUFFIX,168sex.top
DOMAIN-SUFFIX,a7sex.com
DOMAIN-SUFFIX,ctotires.com
DOMAIN-SUFFIX,ferryclean.com
DOMAIN-SUFFIX,zhimeishe888.com
