# zhubajie
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zhubajie.list | 规则数: 5
DOMAIN-SUFFIX,tianpeng.com
DOMAIN-SUFFIX,zbj.com
DOMAIN-SUFFIX,zbjdev.com
DOMAIN-SUFFIX,zbjimg.com
DOMAIN-SUFFIX,zhubajie.com
