# zte
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zte.list | 规则数: 7
DOMAIN-SUFFIX,nubia.cn
DOMAIN-SUFFIX,nubia.com
DOMAIN-SUFFIX,redmagic.com
DOMAIN-SUFFIX,ztedevices.com
DOMAIN-SUFFIX,ztemall.com
DOMAIN-SUFFIX,ztems.com
DOMAIN-SUFFIX,zte.com.cn
