# zto-express
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zto-express.list | 规则数: 13
DOMAIN-SUFFIX,ztoapp.com
DOMAIN-SUFFIX,izto.com
DOMAIN-SUFFIX,tuxi.com
DOMAIN-SUFFIX,zt-express.com
DOMAIN-SUFFIX,zto.cn
DOMAIN-SUFFIX,zto.com
DOMAIN-SUFFIX,zto.net
DOMAIN-SUFFIX,95311.com
DOMAIN-SUFFIX,ztoglobal.com
DOMAIN-SUFFIX,ztogroup.com
DOMAIN-SUFFIX,ztoyh.com
DOMAIN-SUFFIX,izto.com.cn
DOMAIN-SUFFIX,mlzt.com.cn
