# zuoyebang
# 由 fly-rule 自 metacubex@d4785c3 转换，请勿手工编辑
# 上游: geo/geosite/zuoyebang.list | 规则数: 5
DOMAIN-SUFFIX,zuoyebang.cc
DOMAIN-SUFFIX,zuoyebang.com
DOMAIN-SUFFIX,zybang.com
DOMAIN-SUFFIX,kuaiduizuoye.com
DOMAIN-SUFFIX,syh.zybang.com
