# example
# 由 fly-rule 自 custom/example.list 生成，请勿手工编辑
# 规则数: 6
DOMAIN,foo.example.org
DOMAIN-SUFFIX,example.com
DOMAIN-KEYWORD,tracker
IP-CIDR,192.0.2.0/24
IP-CIDR6,2001:db8::/32
PROCESS-NAME,Transmission
